.github/workflows/codeql.yaml

Increase timeout to accommodate codeQL runtime on windows.

fix: increase CodeQL timeout

---

captureworkload/main.go
controller/main.go
deploy/manifests/controller/helm/retina/values.yaml
docs/troubleshooting/basic-metrics.md
init/retina/main_linux.go
operator/main.go
pkg/capture/capture_manager.go
pkg/managers/controllermanager/controllermanager.go
pkg/telemetry/telemetry.go

Adding docs and checks for better clarify where and how telemetry is enabled. Also fix a bug where `TrackPanic` is invoke even though telemetry is not enabled.

chore: add clarity to telemetry enablement

---

.devcontainer/devcontainer.json
.devcontainer/installMoreTools.sh
README.md

Adding Dev Container config and "Open in Codespaces" button at the top of the README.

feat: adding devcontainer config

---

.github/workflows/release-images.yaml

The kubectl-retina job was removed in #112. Remove the dependency on it from the manifests job so that images may be published.

fix: drop dependency on remove kubectl-retina job

---

.goreleaser.yaml

Publishing plugins to Krew requires the plugins to be packaged as .zip or .tar.gz archives.

chore: package kubectl retina as tar.gz (zip for windows) via goreleaser

---

.github/workflows/release-charts.yaml
deploy/manifests/controller/helm/retina/Chart.yaml
deploy/manifests/controller/helm/retina/values.yaml

Publishes the helm chart to `ghcr.io/<repo>/charts/<chart>:<tag>` on tag.
Sample run: https://github.com/rbtr/retina/actions/runs/8396910644/job/22999286123#step:5:9
Published artifact: https://github.com/rbtr/retina/pkgs/container/retina%2Fcharts%2Fretina/194747724?tag=v0.0.2
fixes #107

feat: publish charts as OCI artifacts to GHCR

---

controller/Dockerfile.controller

Add missing libraries required for `clang+llvm` to work in agent. Add the missing libs in tools image.
Fixes - https://github.com/microsoft/retina/issues/130
1. Built `amd64` and `arm64` image and deployed them in a K8s cluster with both kind of nodes
2. `agent` pod is up and running in all the nodes

fix(arm64-agent): Add dependencies for arm64

---

.github/dependabot.yaml
.github/workflows/stale.yaml

- updates dependabot to use new labels and adds the tools submodule to its tracking
- updates stale workflow to use new labels and shortens the stale timer to 7 days, with 7 additional days to close

chore: update GHA workflows

---

deploy/manifests/controller/helm/retina/templates/daemonset.yaml

This duplicate will lead to problems using automated CD tools like fluxCD:
`2024-03-27T14:57:44.805Z error HelmRelease/retina.retina - Reconciler error Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 119: mapping key "nodeSelector" already defined at line 27`

fix(helm): remove duplicate nodeSelector

---

controller/Dockerfile.controller
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022

This update caches Go’s build artifacts, speeding up image builds and avoiding rebuilds for unchanged packages, thus streamlining development.

feat: cache Go's build artifacts in dockerfiles

---

deploy/manifests/controller/helm/retina/templates/daemonset.yaml
deploy/manifests/controller/helm/retina/templates/podmonitor.yaml
deploy/manifests/controller/helm/retina/values.yaml

Add support for podMonitor in helm chart.
Testing done:
- podmonitor generated
- prometheus discovered it

feat(helm): add podmonitor

---

.github/workflows/trivy.yaml

Adds Trivy to scan containers. 
This workflow will run:
- after "Release Retina Container Images" which runs on every tag and commit to main
- daily on main
- on-demand via `workflow_dispatch`
Validated in my fork: https://github.com/rbtr/retina/actions/runs/8528872075/job/23363583626

feat: add trivy

---

pkg/controllers/cache/cache.go

Prevent namespace controller from causing unnecessary reconciliation.
Namespace controller causes unnecessary reconciliation of metrics module (#233)
The elements of the namespace array returned by GetAnnotatedNamespaces() are in random order, so
If there are more than one annotated namespace, the namespace controller may call Reconcile() with a different spec than before.

fix: metrics module repeats unnecessary reconciliation (#233)

---

.gitignore
site/sidebars.js

Two new documentation pages were added but aren't in the site nav so are not discoverable. Adds them to the correct sidebar navigation categories. 
Tested locally:

fix: add new site pages to nav

---

deploy/manifests/controller/helm/retina/templates/daemonset.yaml
deploy/manifests/controller/helm/retina/templates/operator.yaml
deploy/manifests/controller/helm/retina/values.yaml

Currently the resources for the retina operator are non-configurable. And the agent only has limits configurable which sets the requests at the same value. With the default cpu limit for the agent being 500m, this seems excessive for request.
I have added what I think are sane defaults, but if you think other values are appropriate let me know.
N/A
N/A
N/A
---

feat(helm): Improve resource configuration in chart

---

internal/ktime/ktime.go
internal/ktime/ktime_other.go
internal/ktime/ktime_unix.go
pkg/plugin/dropreason/_cprog/drop_reason.c
pkg/plugin/dropreason/dropreason_linux.go
pkg/plugin/packetparser/_cprog/packetparser.c
pkg/plugin/packetparser/packetparser_linux.go

Adjusts timestamps from eBPF that use the kernel monotonic timer to UTC during Flow ingestion. 
This is done on a best-effort basis, because it is impossible to sample from the monotonic timer and the wall-clock at the same instant. The difference in the time it takes to execute these instructions should be small enough for our purposes in practice. 
Fixes #204 
This is effectively only implemented for Unix builds as I don't know how Windows ktime behaves (and we're only compiling these plugins for Linux at the moment). It can be implemented on !unix in the future as necessary. 
---

fix: convert kernel monotonic times to wall time

---

cli/cmd/capture/capture.go
cli/cmd/capture/create.go
cli/cmd/capture/delete.go
cli/cmd/capture/download.go

The `-n,--name` flag on `retina capture download` conflicts with the inherited `-n,--namespace` flag from `cli-runtime`. 
This change removes the shorthand `-n` from the `--name` flag.
Additionally, it: 
- changes the `--name` flag to be "Persistent" on the `capture` command instead of only declared on some subcommands
- marks the `--name` flag "Required" and removes unnecessary manual checks that the value is set
- respect the `--name` flag during `create` instead of generating a randstring
Add any additional notes or context about the pull request …

fix: capture name flag

---

pkg/plugin/packetparser/_cprog/packetparser.c
pkg/plugin/packetparser/_cprog/packetparser.h

This pull request fixes the compatibility with Cilium. Both Cilium and Retina attach tc-bpf programs to the host interfaces of pods and, depending on the configuration for Cilium, to the native devices (eth0 & co). As a result, whichever program is executed first bypasses the other program. Since Cilium relies on its BPF programs to implement service handling, policy enforcement, and much more, a bypass can have dire consequences.
To avoid bypassing Cilium, Retina needs to return TC_ACT_UNSPEC instead of TC_ACT_OK; that return code will cause subsequent BPF programs attach at the same tc hook to be executed [1]. In addition, Cilium should be run with `--bpf-filter-priority=2` to always run after Retina.
This change was tested on a 5-nodes GKE cluster with Cilium installed. The full …

fix: Don't bypass other tc-bpf programs

---

.github/workflows/codeql.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/goreleaser.yaml
.github/workflows/images.yaml
.github/workflows/release-images.yaml
.github/workflows/test.yaml

Sets the GHA `setup-go` Go version from the go.mod, instead of separately.
---

fix: set go version from mod

---

.github/workflows/commit-message.yaml

@robertprast in #285 and @random-dudde over at https://github.com/random-dudde/retina/pull/1 are poking at the [commit-message](https://github.com/microsoft/retina/blob/30a128b985bc99fc8686ef21afa1cc7358dc7dfd/.github/workflows/commit-message.yaml) Action trying to pull off a bash escape exploit.
The bash escape actually exists, due to the direct usage of the PR title:
```bash
commit_msg_header="${{ github.event.pull_request.title }}"
```
**However, this is not readily exploitable** because we require approval to run workflows on _all_ external contributions. A maintainer would need to approve the workflow, which makes it unlikely that any useful bash could be sneakily stuffed in to the title and executed.
Even getting workflow approval with a benign title and then updating it later is …

chore: prevent action bash escapes

---

pkg/common/endpoint.go
pkg/common/ipaddr.go
pkg/controllers/cache/cache.go
pkg/controllers/cache/cache_test.go
pkg/enricher/enricher_test.go

Fixes #224 
Both the previous implementation and this PR don't clear stale IP-endpoint bindings immediately from the ipToEpKey Map.
E.g. When endpoint A changes from IP address "1.1.1.1" to "2.2.2.2", the stale binding between the IP address "1.1.1.1" and endpoint A is still in the ipToEpKey map until the IP address "1.1.1.1" gets reassigned to another pod.
However, this shouldn't be a problem. The DNS is supposed to provide up-to-date IP addresses for the sender and receiver so that any flow event will always contain the latest IP addresses.

fix: add secondary IPs for enrichment

---

.github/workflows/goreleaser.yaml
.github/workflows/images.yaml
.github/workflows/release-images.yaml

Bumping actions/setup-go v4 -> v5 and azure/login v1 -> v2
---

chore: bump github actions version

---

Makefile
deploy/grafana/dashboards/clusters.json
deploy/grafana/dashboards/dns.json
deploy/grafana/dashboards/pod-level.json
deploy/grafana/dashboards/simplify-grafana-overwrite_test.go
deploy/grafana/dashboards/simplify-grafana.go
deploy/grafana/dashboards/simplify-grafana_test.go

When it comes to JSON for Grafana dashboards, it seems best practice to remove a bunch of unnecessary pieces like the name of your personal datasource, current variable selection, etc. This PR:
1. Introduces `make simplify-dashboards` to automate this tedious process.
2. Adds a unit test to ensure authors run this command.
```bash
$ make simplify-dashboards 
cd deploy/grafana/dashboards/ && go test . -tags=dashboard,simplifydashboard -v
=== RUN   TestOverwriteDashboards
simplify-grafana-overwrite_test.go:22: simplifying/overwriting dashboard: clusters.json
simplify-grafana-overwrite_test.go:22: simplifying/overwriting dashboard: dns.json
simplify-grafana-overwrite_test.go:22: simplifying/overwriting dashboard: pod-level.json
--- PASS: TestOverwriteDashboards (0.02s)
PASS
ok …
```

tool(grafana): test/tooling to ensure dashboards are simplified/importable

---

deploy/manifests/controller/helm/retina/templates/podmonitor.yaml

Error during Helm templating if we pass some additional labels to the PodMonitor resources
Before:
```
$ helm template . -f values.yaml --set metrics.podMonitor.enabled=true --set metrics.podMonitor.additionalLabels"foo"=bar
Error: template: retina/templates/podmonitor.yaml:10:62: executing "retina/templates/podmonitor.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}
```
After:
```
$ helm template . -f values.yaml --set metrics.podMonitor.enabled=true --set metrics.podMonitor.additionalLabels"foo"=bar
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
name: retina-svc
namespace: kube-system
labels:
k8s-app: retina
foo: bar
spec:
podMetricsEndpoints:
- port: retina
path: /metrics
interval: 30s
scrapeTimeout: 30s
scheme: http …
```

fix(helm): PodMonitor additional labels YAML

---

controller/main.go
init/retina/main_linux.go
pkg/bpf/setup_linux.go
pkg/log/zap.go
pkg/log/zap_test.go

Refactoring to the `log` package.
Corrects persistent field support, returns error and logger from constructor, inlines log core creation and addition, removes unnecessary helper functions and uses zap ones directly.
---

fix: restructure logger for persistent fields

---

.github/workflows/stale.yaml

s/stale-pr-label**s**/stale-pr-label
https://github.com/actions/stale?tab=readme-ov-file#list-of-input-options
This is why PRs are being labelled with `Stale` instead of the configured `meta/waiting-for-author` 🙁 
---

fix: stale bot PR label

---

pkg/plugin/common/common_linux.go
pkg/plugin/dns/dns_linux_test.go

IG recently changed the return code of the DNS gadget and moved to gopacket - https://github.com/inspektor-gadget/inspektor-gadget/blame/6a5937bba8f13fee889a24340f309d57e8ecabb6/pkg/gadgets/trace/dns/tracer/tracer.go#L168 . Fix the map in utils.
Fix: https://github.com/microsoft/retina/issues/330
---

fix: Fix missing return code for dns response

---

Makefile
controller/Dockerfile
controller/main.go

Build pipeline is green even though build was failed. This PR introduced `set -e` in the build process so the pipeline will fail fast on any error during build. Also moved the `go generate` part to an intermediate stage so we can reuse it for `controller-bin` and `init-bin`
---

fix: fail pipeline on failure to build/push image

---

deploy/manifests/controller/helm/retina/templates/podmonitor.yaml

Update matchLabels from https://github.com/microsoft/retina/pull/324
Corrects the match label to use new k8s labels introduced in #324 
Generated yaml:
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
name: retina-svc
namespace: kube-system
labels:
k8s-app: retina
helm.sh/chart: retina-0.0.1
app.kubernetes.io/name: retina
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "0.0.1"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/part-of: retina
app.kubernetes.io/component: metrics
spec:
podMetricsEndpoints:
- port: retina
path: /metrics
interval: 30s
scrapeTimeout: 30s
scheme: http
namespaceSelector:
matchNames:
- kube-system
selector:
matchLabels:
app.kubernetes.io/name: retina
app.kubernetes.io/instance: release-name …
```

fix: correct selector in PodMonitor

---

pkg/plugin/dropreason/dropreason_linux.go
pkg/plugin/dropreason/dropreason_linux_test.go
pkg/plugin/packetparser/packetparser_linux.go
pkg/plugin/packetparser/packetparser_linux_test.go

Fixes issue mentioned in https://github.com/microsoft/retina/issues/319
https://github.com/microsoft/retina/issues/319

fix: only invoke Generate once for plugins when reconciling in plugin manager

---

controller/Dockerfile
pkg/plugin/dropreason/dropreason_linux.go
pkg/plugin/filter/filter_map_linux.go
pkg/plugin/packetforward/packetforward_linux.go
pkg/plugin/packetparser/packetparser_linux.go
test/image/Dockerfile

Migrates the images from Ubuntu/Debian builder and Debian-distroless final image to Mariner for everything. Incidentally also moves from clang-14 to clang-16.

feat: migrate to Mariner containers

---

docs/intro.md

After much experimentation, the minimum required Linux kernel version is v5.4. This documents this fact in the intro documentation so that user expectations are set early.

docs: Document minimum linux kernel version

---

controller/Dockerfile

Pin the Windows base images by SHA. A good security practice, but also a fix to the build because the latest servercore:ltsc2019 image is broken.
https://github.com/microsoft/Windows-Containers/issues/493

fix: pin Windows base images

---

.github/workflows/e2e.yaml
.github/workflows/images.yaml

Part 1: Moves the E2E to a separate GHA to logically separate it from other checks
will follow up to remove e2e from Images workflow entirely.

chore: move E2E to separate GHA

---

docs/captures/cli.md
docs/captures/readme.md

Since `--name` is required to create a capture through CLI, we need to update the capture create command examples in docs.
fix https://github.com/microsoft/retina/issues/410
Not required
---

fix: add --name for capture create command examples

---

docs/captures/readme.md
pkg/capture/outputlocation/blob.go
pkg/capture/outputlocation/blob_test.go

When reading a blob SAS URL from a secret, the URL can have a new line and is surrounded by double quotes. To fix this, we need trim the URL before passing it to blob client.
fix https://github.com/microsoft/retina/issues/132
```
ts=2024-05-29T16:34:16.092Z level=info caller=outputlocation/blob.go:46 msg="Upload capture file to blob." location=BlobUpload
ts=2024-05-29T16:34:17.944Z level=info caller=outputlocation/blob.go:84 msg="Done for uploading capture file to storage account" location=BlobUpload
```
---

fix: trim blob SAS URL read from mounted secret file

---

controller/Dockerfile

Refactor the Dockerfile to pull all external image refs to the top and pin them to SHA refs, then use them by alias throughout the build stages.
---

refactor: pin and alias base images in the Dockerfile

---

pkg/utils/flow_utils.go
pkg/utils/utils_linux_test.go

The `subType` field for flows of type Drop needs to be the DropReason, not the point of observation.
Checked the flows through debug logging to make sure the SubType is set correctly.
---

fix: correctly assign the subtype value in flow for drop reason

---

docs/contributing/developing.md

Updated LLVM version to 16 in `docs/contributing/developing.md` file.
Issue #425 
Should we consider updating the LLVM version in `.devcontainer/installMoreTools.sh` too ?
---

fix: updated llvm version in docs to 16

---

test/e2e/scenarios/dns/scenarios.go

Ref: https://github.com/microsoft/retina/issues/415. Added for Basic DNS metrics but missed for Adv DNS metrics
---

fix(e2e): add an extra nslookup when testing for advanced DNS metrics

---

controller/main.go

As description. Closes https://github.com/microsoft/retina/issues/431. Tested on a cluster, controller-runtime no longer complain about missing SetLogger
---

fix: invoke SetLogger for controller-runtime manager

---

.github/workflows/release-charts.yaml
.github/workflows/release-images.yaml

fix: signing images based on matrix and only run release charts on tags

---

deploy/hubble/manifests/controller/helm/retina/templates/operator/clusterrolebinding.yaml
deploy/hubble/manifests/controller/helm/retina/templates/operator/deployment.yaml
deploy/hubble/manifests/controller/helm/retina/templates/operator/serviceaccount.yaml

This fixes the operator deployment actually using the namespace defined in the helm values. Without this fix, the deployment will fail, since the configuration ConfigMap for the operator is deployed in the specified namespace while the operator itself is deployed in `kube-system`.
Fixes #492

fix: operator deployment ignores custom namespace

---

.pipelines/cg-pipeline.yaml
controller/Dockerfile.windows-native
controller/Dockerfile.windows-native.dockerignore
pkg/plugin/windows/pktmon/pktmon_plugin_windows.go

Occasionally the grpc stream experiences transient errors, which are mitigated by recreating the client observer stream. Requires further RCA, but this avoids crashloopbackoff, and gracefully logs to continue
---

feat: pktmon client recreation + remove ltsc2019 in azp

---

Makefile
captureworkload/main.go
cmd/hubble/cells_linux.go
cmd/hubble/daemon_main_linux.go
cmd/hubble_linux.go
cmd/legacy/daemon.go
controller/Dockerfile
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
controller/Dockerfile.windows-native
init/retina/main_linux.go
internal/buildinfo/buildinfo.go
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022
operator/cmd/cilium-crds/cells_linux.go
operator/cmd/cilium-crds/root_linux.go
operator/cmd/cilium-crds/zap_linux.go
operator/cmd/legacy/deployment.go

As title. These will be populated by the Go compiler via the -ldflags during build. Also fixed https://github.com/microsoft/retina/issues/530
---

fix: move version and appinsightsID to a centralized location (internal/buildinfo)

---

pkg/plugin/infiniband/filesystem_test.go
pkg/plugin/infiniband/infiniband_linux.go
pkg/plugin/infiniband/infiniband_stats_linux.go
pkg/plugin/infiniband/infiniband_stats_linux_test.go
pkg/plugin/infiniband/types_linux.go

Fixes some issues in the infiniband plugin/tests.
After testing, IB stats are successfully exposed through Retina:
```text
networkobservability_infiniband_counter_stats{device="mlx5_0",port="1",statistic_name="VL15_dropped"} 0
networkobservability_infiniband_counter_stats{device="mlx5_0",port="1",statistic_name="excessive_buffer_overrun_errors"} 0
networkobservability_infiniband_counter_stats{device="mlx5_0",port="1",statistic_name="link_downed"} 0
networkobservability_infiniband_counter_stats{device="mlx5_0",port="1",statistic_name="link_error_recovery"} 0
networkobservability_infiniband_counter_stats{device="mlx5_0",port="1",statistic_name="local_link_integrity_errors"} 0
networkobservability_infiniband_counter_stats{device="mlx5_0",port="1",statistic_name="multicast_rcv_packets"} 0 …
```

fix: update readdirs in infiniband plugin

---

.pipelines/cg-pipeline.yaml
cmd/legacy/daemon.go

AZP didn't pass build pipeline vars to makefile recipes
---

chore: fix azp telemetry injection

---

cmd/legacy/daemon.go
pkg/telemetry/telemetry.go
pkg/telemetry/telemetry_test.go

Add runtime profile metrics to the heartbeat for long term performance metrics.
---

feat: add runtime telemetry to heartbeat

---

deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml

Mounts /sys/class/net and /sys/class/infiniband to the Linux daemonset when the `infiniband` plugin is enabled via Helm. Incidentally fixes some templating whitespace.
<details><summary>Before</summary>
```yaml
volumeMounts:
- name: bpf
mountPath: /sys/fs/bpf
- name: cgroup
mountPath: /sys/fs/cgroup
- name: config
mountPath: /retina/config
- name: debug
mountPath: /sys/kernel/debug
- name: tmp
mountPath: /tmp
- name: trace
mountPath: /sys/kernel/tracing
terminationGracePeriodSeconds: 90 # Allow for retina to cleanup plugin resources.
volumes:
- name: bpf
hostPath:
path: /sys/fs/bpf
- name: cgroup
hostPath:
path: /sys/fs/cgroup
- name: config
configMap:
name: retina-config
- name: debug
hostPath:
path: /sys/kernel/debug
- name: tmp
emptyDir: {}
- name: trace
hostPath:
path: …
```

fix: mount ib and net dirs when ib plugin enabled

---

controller/Dockerfile

There's no reason to continually do things like fetching eBPF compilation dependencies, rebuild eBPF, fetch Go dependencies, etc. over and over.  Most of these things will not change frequently, so deserve to be aggressively cached by Docker layers. The things that are more likely to change can then have a much faster build process.
This entailed reducing some of the intermediate image sprawl into a single "bins" image so that cache layers could be reused.

feat: Improve controller Dockerfile caching

---

pkg/plugin/linuxutil/ethtool_handle_linux.go
pkg/plugin/linuxutil/ethtool_stats_linux.go
pkg/plugin/linuxutil/ethtool_stats_linux_test.go
pkg/plugin/linuxutil/linuxutil_linux.go
pkg/plugin/linuxutil/types_linux.go
pkg/plugin/packetparser/packetparser_linux.go

1.Implement a dynamic temporary cache that tracks network interfaces that do not support the ethtool operation.
2.Add new test cases for the new changings
---

fix: Implement a dynamic temporary cache that tracks network interfaces that do not support the ethtool operation.

---

docs/02-Installation/03-Config.md

Annotation in this page is different than [here](https://retina.sh/docs/metrics/annotations/) and it does not work correctly. 
---

fix: annotation tag in documentation

---

test/e2e/framework/types/job.go
test/e2e/framework/types/scenarios_test.go
test/e2e/framework/types/step.go
test/e2e/scenarios/dns/scenarios.go
test/e2e/scenarios/drop/scenario.go
test/e2e/scenarios/latency/scenario.go
test/e2e/scenarios/tcp/scenario.go

chore: fix typo in e2e

---

pkg/plugin/conntrack/_cprog/conntrack.c

if `observation_point` is 0, and we compared it with `OBSERVATION_POINT_FROM_ENDPOINT`, which is also 0, this will evaluate to `false`, which is not what we want.
Logs show all flows with correct traffic direction
```
retina ts=2024-09-10T16:41:11.983Z level=info caller=packetparser/packetparser_linux.go:612 msg="Received flow event" flow="time:{seconds:1725986471 nanos:983049821} verdict:FORWARDED IP:{source:\"100.64.0.196\" destination:\"13.107.21.200\" ipVersion:IPv4} l4:{TCP:{source_port:50818 destination_port:80 flags:{SYN:true}}} Type:L3_L4 event_type:{type:4 sub_type:3} traffic_direction:EGRESS …
```

fix: correctly determine traffic direction in conntrack

---

pkg/plugin/dropreason/_cprog/drop_reason.c

For all eBPF program in the DropReason plugin (except `inet_csk_accept` which has issue we need to investigate https://github.com/microsoft/retina/issues/715):
- only make ebpf map calls when necessary
- omit setting some packet fields to 0 right after `memset` is called on the entire struct
**Details**:
Previously, we did a map lookup regardless of whether the input `retVal` indicated a drop. Now, only for drops. 
We also skip a map delete when there wasn't a earlier kprobe that saved the corresponding PID.

fix: optimize DropReason eBPF map lookups

---

Makefile
controller/Dockerfile

As title. Verified that is it still working with Retina running with older version of Cilium.
---

chore: bump Hubble CLI to v1.16.1

---

docs/07-Contributing/developing.md

Fixed the instructions for LLVM/Clang Installation and cleaned up Environment Config to mention Go, Docker and jq as pre-requisites.
---

fix(docs): update developing instructions

---

pkg/plugin/linuxutil/linuxutil_linux.go
pkg/plugin/packetforward/packetforward_linux.go

Linuxutil and packetforward plugin, these SetupChannel func are not supported setup channel; in order to reduce the unnecessary error log in Kusto, we change the caller level
---

chore: change the setupchannel caller level from warn

---

docs/04-Captures/cli.md

Update documentation to include `kubectl` prefix in the commands to remain consistent with the rest of the page.
https://github.com/microsoft/retina/issues/733
---

fix(docs): add kubectl to retina commands

---

docs/02-Installation/04-Grafana/prometheus-unmanaged.md

1. fix broken path for Prometheus values.yaml path (Helm deployment)
2. clean-up the bullet points numbering
---

fix(docs): update values.yaml path for prometheus

---

deploy/legacy/prometheus/values.yaml

* update additionalScrapeConfigs to filter containers named `retina` (retina agent)
* this will exclude retina-operator container in retina-operator pod
fix #177 
Deployed unmanaged Prometheus as per doc instructions, [see here](https://retina.sh/docs/Installation/Grafana/prometheus-unmanaged#configuring-prometheus)
The target for retina-operator is no longer appearing since it is no longer scraped
---
Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on …

fix(bug): update scrapeConfig to filer retina container specifically

---

pkg/controllers/daemon/service/controller.go
pkg/controllers/daemon/service/controller_test.go

* update service controller to ignore headless svc and re-trigger reconcile when encountering one
* create test to validate UpdateRetinaSvc still throws an error if a retina svc has no IPv4 (this is to make sure existing validation post retinaSvc creation is not broken)
fix #547 
---

fix(bug): ignore headless svc to prevent error messages

---

deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml
deploy/legacy/manifests/controller/helm/retina/values.yaml

Added support for `affinity`, `readinessProbe` and `custom probes`.
Affinity:
Probes:

feat(helm): Added support for affinity, readinessProbe and custom probes

---

pkg/managers/pluginmanager/pluginmanager.go

Plugins should be started as soon as possible, arbitrary delay based off number of enabled plugins isn't helpful to getting metrics delayed from retina start.
---

fix: start plugins in parallel

---

cmd/legacy/daemon.go
cmd/legacy/daemon_linux.go
cmd/legacy/daemon_windows.go

Add OS specific implementation for removing memory lock on Linux/Windows nodes.
Fixes https://github.com/microsoft/retina/issues/790
- Can build/run manually
- Pipelines
---

fix: Implement OS specific mechanism to remove memory lock for plugins

---

deploy/hubble/manifests/controller/helm/retina/templates/hubble/tls-cronjob/rolebinding.yaml

Use minimal required RBAC. CronJob only needs access to secrets in its namespace.
Secrets were still created, Hubble Relay ran with no issues, and `hubble observe flows` works

fix: scope Hubble TLS CronJob's secret access to its namespace

---

operator/cilium-crds/k8s/fakeresource.go
operator/cilium-crds/k8s/resources.go

Retina Operator deletes endpoints when processing Pod delete events, but if for some reason an endpoint exists after its Pod was deleted, then endpoint GC comes into play.
Endpoint GC was broken because it was failing to watch CiliumNodes. Fix by using a fake CiliumNodes resource.
Fixes #598 (logs and details there)
Manual testing. Operator e2e's are WIP in another PR.

fix(operator): broken CiliumEndpoint garbage collection

---

deploy/hubble/manifests/controller/helm/retina/templates/operator/clusterrole.yaml

Use minimal required RBAC. Retina Operator only needs to manage CiliumEndpoints and CiliumIdentities.
Note: `create` cannot be scoped to resourceNames per the k8s documentation: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources
Trying to scope `create` resulted in CrashLoop for Retina operator with the error:
```
unable to create CRDs: Unable to create custom resource definition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:retina-operator\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" function="github.com/Azure/retina-enterprise/operator/k8s/apis.createCRDs.func1 (workspace/operator/k8s/apis/cell.go:61)
```
CRDs were created. …

fix: scope operator's CRD permissions to cilium endpoints/identities

---

.gitignore
deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml
test/e2e/README.md
test/e2e/framework/azure/create-cluster-with-npm.go
test/e2e/framework/kubernetes/create-kapinger-deployment.go
test/e2e/framework/kubernetes/exec-pod.go
test/e2e/framework/kubernetes/get-logs.go
test/e2e/framework/kubernetes/install-retina-helm.go
test/e2e/framework/kubernetes/no-crashes.go
test/e2e/framework/kubernetes/port-forward.go
test/e2e/framework/kubernetes/wait-pod-ready.go
test/e2e/framework/prometheus/prometheus.go
test/e2e/jobs/jobs.go
test/e2e/retina_e2e_test.go
test/e2e/scenarios/windows/scenario.go
test/e2e/scenarios/windows/validate-hns-metrics.go

test: Windows HNS e2e and no crashes step

---

docs/04-Captures/managed-storage-account.md
pkg/controllers/operator/capture/controller.go

This change allows the operator to remove only the managed secret, and ignore NOTFOUND error.
- When removing the Capture with managed secret, it will delete the jobs and secret
```
ts=2024-08-26T07:51:27.757Z level=info caller=capture/controller.go:369 msg="Removing Capture" Capture=default/capture-pod-blobupload
ts=2024-08-26T07:51:27.774Z level=info caller=capture/controller.go:387 msg="Capture jobs are removed" Capture=default/capture-pod-blobupload
ts=2024-08-26T07:51:27.783Z level=info caller=capture/controller.go:402 msg="Capture secret is …
```

fix(capture): remove only managed secret

---

deploy/hubble/prometheus/values.yaml

Adding Hubble scrap job for Prometheus as legacy [values.yaml](https://github.com/microsoft/retina/blob/main/deploy/legacy/prometheus/values.yaml) does not include [Hubble scrape job](https://learn.microsoft.com/en-us/azure/aks/advanced-network-observability-bring-your-own-cli?tabs=non-cilium#visualization-using-grafana).
---

fix: Add Hubble Scrape Job for Prometheus

---

hack/tools/kapinger/clients/http.go
hack/tools/kapinger/config/config.go
hack/tools/kapinger/main.go
hack/tools/kapinger/servers/server.go
test/prometheus/ama-metrics-node/prometheus-config
test/prometheus/ama-metrics/prometheus-config
test/prometheus/create-cm.sh
test/prometheus/prometheus-config
test/prometheus/service.yaml
test/trafficgen/kapinger.yaml

Provide request burst and interval for Kapinger, used to tune volume of http requests
---

feat: kapinger add burst delay and interval

---

cli/cmd/capture/capture.go
cli/cmd/capture/create.go
cli/cmd/trace.go
docs/04-Captures/cli.md
pkg/capture/crd_to_job.go
pkg/capture/utils/capture_image.go

This PR aims to improve the usability of the `retina capture create` command.
New defaults have been set, eliminating the need for required flags. The command can now be ran with just `kubectl retina capture create`.
The documentation received another overhaul - restructuring how flags are displayed into a more readable table and curating the examples which are shown.
Issue related to updating usability of captures
https://github.com/microsoft/retina/issues/766
---

chore: Streamline Usability of Captures

---

test/e2e/framework/azure/create-cluster-with-npm.go
test/e2e/framework/kubernetes/exec-pod.go
test/e2e/framework/kubernetes/port-forward.go

This pull request includes several changes to improve the reliability and efficiency of the Kubernetes end-to-end testing framework. The most important changes involve adjusting timeouts and retry mechanisms to enhance robustness and reduce wait times.
* [`test/e2e/framework/kubernetes/exec-pod.go`](diffhunk://#diff-ebfee2072870c7e30ca7222eab3f94550af60a5ac8de53aa632a949fcd4fd667L42-R54): Added retry logic using `retry.OnError` for executing commands in a pod to handle transient errors more gracefully.
* [`test/e2e/framework/kubernetes/port-forward.go`](diffhunk://#diff-ed249ad2b2805041dfd7ff7466005e33aa4a55adc7728524f6c060af8131dd61L22-R30): Enabled exponential backoff in the default retrier to improve the efficiency of retry attempts.
* …

fix: improve resiliency for e2e tests by adding tweaking retries and timeouts (partially fixes #449)

---

pkg/telemetry/heartbeat_windows.go

Kusto complain the system cannot find the powershell path in Windows, I noticed in windows we are currently hardcoding the powershell path in hpc folder, since the windows powershell in PATH environment variable lost issue was fixed, we should change it back instead of hard code the path
---

fix: Set PowerShell path using environment variables

---

docs/07-Contributing/developing.md

* update contributing doc to add a note about signing commits by default
* add instructions for  codespaces users to use GPG to sign commits
---

fix(docs): update doc, codespaces config and GHA on commit GPG signed

---

test/e2e/framework/kubernetes/create-agnhost-statefulset.go
test/e2e/scenarios/dns/scenarios.go
test/e2e/scenarios/drop/scenario.go

This pull request includes changes to improve the end-to-end resiliency in DNS scenarios. The changes include:
- Added a delay to guarantee that the pods will have the BPF program attached before executing further steps in the scenario.
- Updated the label selector for the `CreateDenyAllNetworkPolicy` step to target the `agnhost-drop` pods instead of `agnhost-a` pods.
- Updated the `CreateAgnhostStatefulSet` step to use the `agnhost-drop` name instead of `agnhost-a`.
- Updated the `ExecInPod` steps to target the `agnhost-drop-0` pod instead of `agnhost-a-0`.
- Updated the `ValidateRetinaDropMetric` step to use the `agnhost-drop` source instead of `agnhost-a`.
- Updated the `DeleteKubernetesResource` step to target the `agnhost-drop` stateful set instead of `agnhost-a`.
It addresses the …

fix(tests): Improve e2e resiliency

---

pkg/plugin/conntrack/_cprog/conntrack.c

We wrongly pass `key` reference to `_ct_should_report_packet` when the connection is found based on the `reverse_key`, this `key` is then removed as part of GC when the connection timed out or if it is a TCP connection and FIN or RST flags are set.
This PR fixes the issue by passing the correct key reference which is `reverse_key`
#807 
---

fix(ct): correctly pass reverse key for deletion from conntrack map

---

pkg/metrics/metrics.go
pkg/plugin/dns/dns_linux.go
pkg/plugin/dns/dns_linux_test.go
pkg/plugin/linuxutil/netstat_stats_linux.go
pkg/plugin/linuxutil/netstat_stats_linux_test.go
test/e2e/framework/prometheus/prometheus.go
test/e2e/scenarios/dns/validate-basic-dns-metric.go
test/e2e/scenarios/tcp/validate-tcp-connection-remote.go

This PR addresses the cardinality issue in two basic plugins. By removing the label from basic dns and excluding localhost and node ip from linux util plugin tcp_connection_remote.
It also adds a check in the e2e to validate metrics without checking specific labels. 
https://github.com/azure-networking/retina-enterprise/issues/263
https://github.com/azure-networking/retina-enterprise/issues/272
```
networkobservability_dns_request_count 80
networkobservability_dns_response_count 50
networkobservability_adv_dns_request_count{ip="10.224.3.111",namespace="kube-system-test",podname="agnhost-adv-dns-port-forward-7215873926146132341-0",query="some.non.existent.domain.",query_type="A",workload_kind="StatefulSet",workload_na …
```

fix(basic-metrics): Remove label from basic dns and filter out IPs from linux util plugins

---

pkg/k8s/cell_linux.go
pkg/k8s/watcher_linux.go

Add CiliumEndpoint and Service objects to IPCache for flow enrichment.
https://github.com/microsoft/retina/issues/536
```bash
Oct 27 18:19:13.348: kube-system/alpine:59204 (ID:45406) -> 10.0.216.107:8080 (world) to-stack FORWARDED (TCP Flags: SYN:true)
Oct 27 18:19:13.350: kube-system/alpine:59204 (ID:45406) <- 10.0.216.107:8080 (world) to-endpoint FORWARDED (TCP Flags: SYN:true  ACK:true)
Oct 27 18:19:13.350: kube-system/alpine:59204 (ID:45406) -> 10.0.216.107:8080 (world) to-stack FORWARDED (TCP Flags: ACK:true)
Oct 27 18:19:13.350: kube-system/alpine:59204 (ID:45406) -> 10.0.216.107:8080 (world) to-stack FORWARDED (TCP Flags: PSH:true  ACK:true)
Oct 27 18:19:13.352: kube-system/alpine:59204 (ID:45406) <- 10.0.216.107:8080 (world) to-endpoint FORWARDED (TCP Flags: PSH:true  ACK:true) …
```

feat(hubble): Add Ciliumendpoint and Service resource to k8s watcher

---

pkg/plugin/conntrack/_cprog/conntrack.c

In conntrack, we should always report any TCP packets that carried important flags such as SYN and URG to userspace, regardless of the report interval.
#908 
Manually verified that we are now capturing the SYN-ACK packet at both point of observation (client and server, when they are deployed on a same node)
`hubble_tcp_flags_total{destination="",family="IPv4",flag="SYN-ACK",source="kube-system/agnhost-flow-intra-1"} 2`
---

fix: report TCP packets that carried important flags regardless of the report interval

---

pkg/plugin/conntrack/conntrack_linux.go

In a high connection churn environment, this log entry can clutter Retina’s logs without providing actionable insights. Since it does not impact Retina’s operation, it is safe to reduce its logging level to debug.
---

fix(log): change log level from error to debug when we failed to delete a key in conntrack

---

Makefile
shell/Dockerfile

Build a new image retina-shell for adhoc network debugging on Linux nodes/pods.
https://github.com/microsoft/retina/issues/910
Tested building with the following commands:
```
IMAGE_REGISTRY=widalytest.azurecr.io BUILDX_ACTION=--push PLATFORM=linux/amd64 make retina-shell-image
IMAGE_REGISTRY=widalytest.azurecr.io BUILDX_ACTION=--push PLATFORM=linux/arm64 make retina-shell-image
IMAGE_REGISTRY=widalytest.azurecr.io BUILDX_ACTION=--push make manifest-shell-image
```
Then ran it locally:
There are two issues with the AzLinux 3 base image that should be fixed in the upcoming AzLinux3 release. See comments in the Dockerfile for details.
---

feat: add retina-shell image for Linux

---

docs/02-Installation/02-CLI.md

There are two "Option 2". Changing the third option to be "Option 3".
na
- [] I have added tests, if applicable.
---

fix(docs): Typo in CLI installation options

---

test/e2e/framework/kubernetes/check-pod-status.go
test/e2e/framework/kubernetes/no-crashes.go
test/e2e/jobs/jobs.go

When assessing the stability of components within a cluster, container restarts can sometimes be ignored if they are expected or non-critical. This pull request adds an attribute to allow the option to ignore container restarts during end-to-end (E2E) cluster confidence tests.
---

fix(test):  check restart separately from ready pods. 

---

shell/Dockerfile

* bpftool/bpftrace don't work from inside the container, so remove them from the image.
* nc is useful for testing TCP connectivity, so add it.
* jq is useful for parsing IMDS output, so add it too.
#910
---

feat: remove bpftool/bpftrace and add nc/jq to retina-shell image

---

.pipelines/cg-pipeline.yaml

Build retina-shell image in .pipelines/cg-pipeline.yaml, which is used to publish to acnpublic.azurecr.io/containernetworking/retina-shell
#910 
N/A
Untested, but follows the same pattern as other release jobs.
---

feat: build retina-shell image in .pipelines/cg-pipeline.yaml

---

controller/Dockerfile

We don't need to generate mocks when building images, since they're not even in the final build products and it is a waste of compute. Having it in here causes spurious errors since we run `go generate` with a throwaway go.mod. This is to improve Docker caching.
Closes #970

fix: Remove mockgen from go generate step

---

.github/workflows/images.yaml
.github/workflows/release-images.yaml
Makefile
cli/Dockerfile
cli/cmd/capture/create.go
cli/cmd/version.go

This changes allow the CI and release pipeline to build and publish kubectl-retina images
- build image:
- image build succeeded
- 
- create manifest
---

feat: build and publish kubectl-retina image

---

controller/Dockerfile
operator/Dockerfile

This pull request includes updates to the base images used in the `controller/Dockerfile`. The changes involve updating the SHA256 digests for several images to ensure the use of the latest versions.
Updates to base images:
* Updated the SHA256 digest for the `golang` image to `8ac5373de7fde69d08c52e4a1ba40e976a543b3e93196f7fe07c3f91853865f3`. (`[controller/DockerfileL6-R12](diffhunk://#diff-df234eb86d676bd9233f232e9dc9af4895969477a6a9ff9161e32621f6ce76d1L6-R12)`)
* Updated the SHA256 digest for the `mariner-distroless` image to `db87903c5d4d9d6760e86a274914efd6a3bb5914c0b5a6c6b35350ec297fea4f`. (`[controller/DockerfileL6-R12](diffhunk://#diff-df234eb86d676bd9233f232e9dc9af4895969477a6a9ff9161e32621f6ce76d1L6-R12)`)
Address Issue #989
---
Please refer to the …

feat: update the digest for golang and mariner-distroless

---

Makefile

docker rate limiting is now impacting buildkit usage. Explicitly pass mcr image
---

fix(buildx): docker fail on pull rate limit, --driver-opt

---

.github/workflows/e2e.yaml
.github/workflows/images.yaml
test/e2e/framework/helpers/helpers.go
test/e2e/framework/kubernetes/check-pod-status.go
test/e2e/framework/kubernetes/create-namespace.go
test/e2e/framework/kubernetes/delete-namespace.go
test/e2e/framework/kubernetes/install-retina-helm.go
test/e2e/framework/scaletest/add-shared-labels.go
test/e2e/framework/scaletest/add-unique-labels.go
test/e2e/framework/scaletest/create-network-policies.go
test/e2e/framework/scaletest/create-resources.go
test/e2e/framework/scaletest/delete-and-re-add-labels.go
test/e2e/framework/scaletest/options.go
test/e2e/framework/scaletest/templates/networkpolicy.go
test/e2e/framework/scaletest/validate-nodes.go
test/e2e/framework/scaletest/validate-options.go
test/e2e/framework/types/background_test.go
test/e2e/framework/types/runner.go
test/e2e/framework/types/scenarios_test.go
test/e2e/jobs/jobs.go
test/e2e/jobs/scale.go
test/e2e/retina_e2e_test.go
test/e2e/scale_test.go

Create Retina E2E Scale tests using test/e2e framework.
---

test: Retina e2e scale test

---

pkg/plugin/linuxutil/ethtool_stats_linux.go

Reduce metric cardinality of `networkobservability_interface_stats` by ignoring lxc and azv virtual interfaces.

fix(ethtool): ignore lxc and azv interfaces

---

pkg/metrics/metrics.go
pkg/plugin/linuxutil/netstat_stats_linux.go
pkg/plugin/linuxutil/netstat_stats_linux_test.go

This PR makes the following changes:
- **Remove Port Label**: The port label is removed from the TCP remote address metrics.
- **Aggregate IP Addresses**: Instead of tracking individual IP addresses, the metrics now use a generalized `AllIPs` string to represent all IP addresses.
---

fix: reduce cardinality for tcp remote address metrics

---

pkg/plugin/linuxutil/linuxutil_linux.go

Reduce cardinality of `interface_stats` by only keeping stats with "err" or "drop" in the name.

fix(ethtool): enable filtering out non-err/drop stats

---

pkg/plugin/conntrack/_cprog/conntrack.c
pkg/plugin/conntrack/conntrack_bpfel_x86.go
pkg/plugin/conntrack/conntrack_linux.go
pkg/plugin/packetparser/packetparser_bpfel_x86.go

* add new member is_direction_unknown to conntrack_entry struct
* set is_direction_unknown to true when the SYN packet is not captured
#919 
---

chore(ct): add flag to mark ct_entry connection direction is unkown

---

.github/workflows/images.yaml
.pipelines/cg-pipeline.yaml

Following https://github.com/microsoft/retina/pull/972, I add kubectl-retina image build into cg-pipleline, and expect this image can be published into MCR.
Run the script locally, and the image build succeeded.
---

fix: add kubectl-retina manifest

---

go.mod

The version is doing the retraction should be higher than the version we want to retract. We will tag the version v0.10.1 with just this change, and then it will retract itself as well.
---

fix: add retraction for v0.10.0 via v0.10.1 in go mod

---

shell/Dockerfile

Add ethtool to retina-shell image. Useful for querying/modifying network driver settings.
#910 
N/A
---

feat: add ethtool to retina-shell image

---

cli/Dockerfile

mariner distroless minimal provides no support to copy the kubectl-retina image from the container. We need more powerful base image to provide command like 
```
command:
- sh
- -c
- cp -L /kubectl-retina /opt/tools/bin
```
---

chore: use mariner core base image for kubectl-retina

---

.devcontainer/devcontainer.json

One of the exist dependency doesn't work well for codespace env build, have changed with necessary update
Related link: https://github.com/devcontainers/features/tree/main/src/azure-cli
Before
After
---

fix: update devcontainer dependency for codespace

---

.devcontainer/devcontainer.json
.github/workflows/perf.yaml

This pull request includes several changes to improve the configuration and workflow for the development environment and performance testing. The most important changes involve updating the Azure CLI feature reference, modifying the conditions for running performance tests, and adjusting the tagging logic for test runs.
Improvements to development environment configuration:
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L11-R11): Updated the Azure CLI feature reference from `ghcr.io/devcontainers-contrib/features/azure-cli:1` to `ghcr.io/devcontainers/features/azure-cli:1`.
Enhancements to performance testing workflow:
* [`.github/workflows/perf.yaml`](diffhunk://#diff-1aa140a875fcb7cae6b4ada7e6e973c4d55179ad046f56465f …

fix: update performance test conditions in workflow

---

cli/Dockerfile

chore: revert: use mariner core base image for kubectl-retina

---

.github/workflows/trivy.yaml

Add recently created images to trivy scan job
---

fix(trivy): add kubectl-retina and retina-shell images to scan job

---

deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml
deploy/hubble/manifests/controller/helm/retina/templates/operator/deployment.yaml
deploy/hubble/manifests/controller/helm/retina/values.yaml
deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml
deploy/legacy/manifests/controller/helm/retina/templates/operator.yaml
deploy/legacy/manifests/controller/helm/retina/values.yaml

Add support for configuring `priorityClassName` for the agent and operator pods.
---

feat(helm): add support for priorityClassName

---

cli/cmd/capture/capture.go
cli/cmd/capture/create.go
cli/cmd/capture/delete.go
cli/cmd/capture/download.go
cli/cmd/capture/list.go

Fix `capture` subcommands to respect the cli-runtime `--namespace` CLI flag.
Closes #477
---

fix: capture commands should respect --namespace

---

docs/07-Contributing/developing.md
site/README.md

Removing mention of Yarn from building docs, since npm is used instead.
https://github.com/microsoft/retina/issues/988
---

chore: Remove yarn from documentation

---

.github/workflows/perf.yaml

This pull request includes updates to the `.github/workflows/perf.yaml` file to correct the conditions for running the performance tests and to improve the process of retrieving the latest tag for the tests.
Changes to workflow conditions and tag retrieval:
* Updated the condition for running the performance test to use `github.event_name` instead of `github.event`. (`.github/workflows/perf.yaml`: [.github/workflows/perf.yamlL23-R23](diffhunk://#diff-1aa140a875fcb7cae6b4ada7e6e973c4d55179ad046f56465f9f0ec592f283caL23-R23))
* Modified the script to retrieve the latest tag using the GitHub API instead of the `git describe` command, ensuring the latest release tag is fetched correctly. (`.github/workflows/perf.yaml`: [.github/workflows/perf.yamlL52-R57](diffhunk://#diff-1aa140a875fcb7cae6b4ad …

fix: fixed failing network perf measurement gh action

---

Makefile
hack/tools/toolbox/go.mod
hack/tools/toolbox/go.sum
hack/tools/toolbox/main.go

chore: update toolbox build

---

cli/cmd/capture/capture.go
cli/cmd_test.go

Fixes NPE related to uninstantiated `Name` pointer 
---

fix: name flag dereference

---

cli/cmd/shell.go
docs/06-Troubleshooting/shell.md
go.mod
go.sum
shell/README.md
shell/attach.go
shell/manifests.go
shell/manifests_test.go
shell/shell.go
shell/validation.go

Implement `retina shell` CLI command for adhoc network debugging of nodes and pods.
#910 
For testing, need to set `RETINA_SHELL_IMAGE_REPO` and `RETINA_SHELL_IMAGE_VERSION` until the retina-shell image is published.
---

feat: implement retina shell CLI command

---

.goreleaser.yaml

When building the Retina CLI locally, `kubectl retina version` showed up normally. After digging around, I found that we haven't update goreleaser with the latest ldflags.
Fix #1013
---

fix(goreleaser): update ldflags for building Retina CLI

---

pkg/managers/filtermanager/cache.go
pkg/managers/filtermanager/cache_test.go
pkg/managers/filtermanager/manager_linux.go

Cache had a TOCTOU initialization race.
Cache tests had data races.
---

fix: filtermanager cache and cache test races

---

docs/06-Troubleshooting/shell.md
shell/Dockerfile

Azure Linux 3.0.20241203 now supports iptables-nft and resolves the SymCrypt warning.
N/A
N/A

chore: update retina-shell image to azlinux 3.0.20241203

---

test/e2e/common/common.go
test/e2e/framework/kubernetes/create-agnhost-statefulset.go
test/e2e/framework/kubernetes/create-network-policy.go
test/e2e/jobs/jobs.go
test/e2e/scenarios/dns/scenarios.go
test/e2e/scenarios/drop/scenario.go
test/e2e/scenarios/tcp/scenario.go

This PR allows us to run plugin e2e in both arm64 and amd64 arch.
It also replaces agnhost image with the standard one hosted in `registry.k8s.io/e2e-test-images`instead of the fork in `acnpublic`, as it is multi-arch and good practice.
The test sets up agnhost in different args, and check plugin metrics on retina-agent on both amd64 and arm64.
[#450](https://github.com/microsoft/retina/issues/450)
---
Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on …

test: Run e2e tests in both arm64 and amd64 arch. 

---

cli/Dockerfile
controller/Dockerfile
controller/Dockerfile.gogen
controller/Dockerfile.proto
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
controller/Dockerfile.windows-cgo
controller/Dockerfile.windows-native
go.mod
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022
test/image/Dockerfile

* Update go version in go.mod to 1.23.4
* Update build images to 1.23.4
n/a
---

chore(go): update go.mod and base images to go 1.23.4

---

.github/workflows/update-hubble.yaml
Makefile
controller/Dockerfile

Introduce a new Github Action workflow that will check for new Hubble version and bumping it if neccesary
Sample PR and Workflow run 
https://github.com/nddq/retina/pull/9
https://github.com/nddq/retina/actions/runs/12438751428
---

feat: automate Hubble version bump

---

Makefile
controller/Dockerfile

bump Hubble from 1.16.3 to 1.16.5
---

deps: bump Hubble from 1.16.3 to 1.16.5

---

pkg/capture/crd_to_job_test.go

Previously, in [PR 894](https://github.com/microsoft/retina/pull/894), timestamps were introduced to be able to print capture names as their jobs were beginning. 
This PR addresses an oversight in the testing which compared whether the timestamp of the test and the timestamp of the test capture were the same. This was not always the case - particularly if there was some delay between the beginning of the test and the beginning of the capture. The change in this PR adds a custom comparer to the `cmp.Diff` which ignores the timestamp environment variables.
[1045](https://github.com/microsoft/retina/issues/1045)
The tests now succeed regardless of whether a delay occurs or not - causing the timestamps to differ. This was simulated with an artificial delay with `time.Sleep`.
---
Please refer …

fix(test): Add custom comparer to ignore timestamps in capture tests

---

test/goldpinger/deployment.yaml
test/scale/example-deployment.yaml
test/trafficgen/kapinger.yaml

The [Retina OSS CG Pipelines](https://dev.azure.com/msazure/One/_build?definitionId=357560&_a=summary) has been generating warnings because of two images that aren't being pulled from MCR: docker.io/bloomberg/goldpinger:v3.9.0 and ghcr.io/microsoft/retina/kapinger:latest.
The two images have been replaces by internal ones.
Full description of the issue and the solution can be found in [[Spike] Investigate Retina OSS Jobs (All Warnings)](https://msazure.visualstudio.com/One/_workitems/edit/30303687).
All warnings have been built successfully and not warning has been flagged.
https://dev.azure.com/msazure/One/_build/results?buildId=111569628&view=results
---
Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for …

build(images): Changing external test images to internal ones

---

.pipelines/cg-pipeline.yaml

Reverting 32ead63 since acndev.azurecr.io represents a vulnerability. The pipeline dependency will be addressed at a future stage using acnprod.azurecr.io instead.
---

build(images): Reverting 32ead63

---

.golangci.yaml

This linter causes more harm than good, encouraging practices that actively obfuscate simple values whose meaning could be derived from context. Since it has no context-awareness, it flags everything from file modes, to obvious iteration counters as "magic numbers." This determination is fairly straightforward for a reviewer to make by hand, and it comes up relatively infrequently. The best course of action, until a better (probably LLM-based) magic number detector can be found.

fix: Remove gomnd from golangci linters

---

.gitignore
Makefile

This PR adds the `escape_dot` function to the Makefile so that secret keys containing dots (e.g., `tls.crt`) are correctly escaped when forming Kubernetes JSONPath expressions. Previously, the lack of an escape function caused the JSONPath to parse `tls.crt` as nested fields, leading to empty certificate files.
https://github.com/microsoft/retina/issues/601 
`[hubble] make get-certs not working`
Changes: 
- Implement `escape_dot` using `$(subst .,\\.,$(1))` in the Makefile
- Update the `get-certs` target to call `escape_dot` when retrieving secrets
- Fix empty cert issue caused by incorrect JSONPath queries
---
Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute …

fix(makefile): add missing escape_dot function to properly handle secret key names with dots

---

.github/workflows/test.yaml
Makefile
test/image/Dockerfile

This PR addresses two issues:
1. Ensuring that `jq` is installed before using it in the Makefile.
2. Adding a `make coverage` step in the GitHub Actions workflow to generate coverage files prior to uploading artifacts.
https://github.com/microsoft/retina/issues/688 
`ci: minor bugs in "Test Retina Image" pipeline`
Changes
- Add a check in the Makefile to fail early if `jq` is not found on the system.
- Update the GitHub Actions workflow to run `make coverage` before the coverage artifacts are uploaded.
---

fix: ensure jq is installed and add coverage generation in GitHub Actions

---

.github/workflows/test.yaml
Makefile

After fixing the artifact upload in GitHub Actions, we discovered a conflict with Azure Pipelines as both systems were using the ./output directory. This was causing issues with Azure Pipeline builds.
[ci: rename GitHub Actions output folder to artifacts #1254](https://github.com/microsoft/retina/issues/1254)
This change resolves the pipeline conflicts while maintaining all existing functionality. It provides better separation between different CI systems.
---

fix(ci): rename GitHub Actions output folder to artifacts

---

docs/02-Installation/01-Setup.md

Add missing `--version` flag to the documentation for installing the Hubble chart.
#1223
---

fix(doc): Add missing --version for Hubble chart install

---

pkg/telemetry/telemetry.go

Add `metricscardinality` to heartbeat. This will give visibility on the number of time series being exposed by retina.
#1040 
Metrics exported with heartbeat:
Metrics of types `histogram` and `summary` expose multiple time series during a scrape. Code is counting according to number of time series exposed at /metrics endpoint.
Ref: 
https://prometheus.io/docs/concepts/metric_types/#histogram
https://prometheus.io/docs/concepts/metric_types/#summary
---

feat: add metricscardinality to heartbeat

---

.github/workflows/scale-test.yaml

fix workflow value `inputs.image_namespace`
---

test: fix value from inputs.image_namespace

---

.github/workflows/stale.yaml

Ignores draft PRs and adds a label to preserve PRs so they don't become stale
---

chore: add exemptions to stale workflow

---

Makefile
controller/Dockerfile

Upgrade Hubble version to 1.16.6 to remediate vulnerability.
---

fix(version-upgrade): Upgrade Hubble Version  to  1.16.6 

---

test/multicloud/Makefile
test/multicloud/examples/aks/outputs.tf
test/multicloud/live/retina-aks/outputs.tf
test/multicloud/modules/aks/outputs.tf
test/multicloud/modules/gke/output.tf
test/multicloud/modules/kind/output.tf
test/multicloud/test/example_aks_test.go
test/multicloud/test/example_gke_test.go
test/multicloud/test/example_kind_test.go
test/multicloud/test/integration_retina_kind_test.go
test/multicloud/test/testUtils.go

* add fetchSensitiveOutputs function to override default logger to prevent sensitive outputs from being logged
* add checkRetinaPodsRunning function to check if Retina pods are running
* add make target for formatting both OpenTofu and go code
* modify make test target to run test ONLY for TestRetinaKindIntegration till we get cloud creds
* refactor tests to use new func
#1267 
---

test(mc): Add function to override logger for sensitive outputs

---

test/e2e/infra/azure_temp_infra_setup.go
test/e2e/scale_test.go

When there's a failure in infra creation, `t.Cleanup` function is not called because it is registered after job's `Run` method is called.
---

fix(test): fix test cleanup

---

pkg/telemetry/telemetry.go
pkg/telemetry/telemetry_test.go

* add nil check in heartbeat's metricscardinality
* add tests for metricscardinality
---

fix(heartbeat): add nil check in heartbeat's metricscardinality

---

.github/workflows/images.yaml
cmd/standard/daemon.go
deploy/standard/manifests/controller/helm/retina/templates/configmap.yaml
deploy/standard/manifests/controller/helm/retina/templates/operator.yaml
deploy/standard/manifests/controller/helm/retina/values.yaml
operator/cmd/standard/deployment.go
operator/config/config.go
operator/config/config_test.go
operator/config/testwith/config-small-telemetry-interval.yaml
operator/config/testwith/config-without-telemetry-interval.yaml
operator/config/testwith/config.yaml
pkg/config/config.go
pkg/config/config_test.go
pkg/config/testwith/config-small-telemetry-interval.yaml
pkg/config/testwith/config-without-telemetry-interval.yaml

* Add APP_INSIGHTS_ID to image build to allow monitoring through heartbeat during test execution.
* Add test to configuration packages (for both operator and daemonset)
* Make heartbeat interval configurable
* New keys in `deploy/standard/manifests/controller/helm/retina/values.yaml`
Manual test was also done to validate that the configuration was propagated from helm chart `values.yaml` file to both operator and agent. Value set was printed to log:
---
Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to …

chore: add APP_INSIGHTS_ID to image build

---

captureworkload/main.go
cli/cmd/capture/create.go
cli/cmd/capture/delete.go
cli/cmd/capture/list.go
cli/cmd/capture/table_util.go
pkg/capture/capture_manager.go
pkg/capture/capture_manager_test.go
pkg/capture/crd_to_job.go
pkg/capture/crd_to_job_test.go
pkg/capture/outputlocation/blob.go
pkg/capture/outputlocation/hostpath.go
pkg/capture/outputlocation/output.go
pkg/capture/outputlocation/output_test.go
pkg/capture/outputlocation/pvc.go
pkg/capture/outputlocation/s3.go
pkg/capture/provider/interface.go
pkg/capture/provider/mock_network_capture.go
pkg/capture/provider/network_capture_unix.go
pkg/capture/provider/network_capture_win.go
pkg/capture/test_helper.go
pkg/controllers/operator/capture/controller.go
pkg/controllers/operator/capture/suite_test.go

Refactoring the capture manager and capture commands to create a context hierarchy by passing it around, rather than creating a new one in each method with `context.TODO`.
https://github.com/microsoft/retina/issues/317
https://go.dev/blog/context
---

chore: Refactor Captures to use Contexts

---

README.md

Hiya, while doing #1326, I've noticed that the document link is not working. this PR is made with an intent to fix that.
You can see working `Captures` here - * https://github.com/Tatsinnit/retina/tree/fix/doclink?tab=readme-ov-file whereas the main repo has broken link for `captueres` which goes to page not found.
---

fix: captures document link not working.

---

.github/workflows/codeql.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/goreleaser.yaml
.github/workflows/images.yaml
.github/workflows/kapinger.yaml
.github/workflows/markdownlint.yaml
.github/workflows/perf.yaml
.github/workflows/release-charts.yaml
.github/workflows/release-images.yaml
.github/workflows/scale-test.yaml
.github/workflows/test-multicloud.yml
.github/workflows/test.yaml
.github/workflows/trivy.yaml
.github/workflows/update-hubble.yaml

I noticed this while doing documentation updated hence a small upgrade PR for help for this repo as well.
This PR introduces explicit version pinning for dependencies to improve build reliability and prevent unexpected issues due to upstream changes. By specifying exact versions, we ensure that all environments—local development, CI/CD pipelines, and production—use the same dependency versions, reducing the risk of breaking changes introduced in newer releases.
1. **Prevents Unexpected Breakages** – Dependency updates can introduce breaking changes or incompatibilities. Pinning ensures stability.  
2. **Ensures Reproducible Builds** – Developers and CI/CD pipelines will run identical dependency versions, reducing “works on my machine” issues.  
3. **Improves Security** – By locking …

fix: Security pin SHA for known workflows.

---

shell/Dockerfile

Install `less` command in retina-shell image.
N/A
N/A
---

feat(shell): install less in retina-shell image

---

shell/Dockerfile

Running `bash -l` causes bash to source /etc/profile, which includes the hostname in the shell prompt.
This is useful for keeping track of where retina-shell is running if you have multiple terminals open.
N/A 
N/A
---

feat(shell): run bash as a login shell to get hostname in prompt

---

.github/workflows/daily-scale-test.yaml
.github/workflows/scale-test.yaml
test/e2e/common/common.go
test/e2e/framework/azure/create-cluster.go
test/e2e/framework/helpers/helpers.go
test/e2e/framework/kubernetes/check-pod-status.go
test/e2e/framework/kubernetes/create-kapinger-deployment.go
test/e2e/framework/kubernetes/create-namespace.go
test/e2e/framework/kubernetes/delete-namespace.go
test/e2e/framework/kubernetes/label-nodes.go
test/e2e/framework/params/params.go
test/e2e/framework/scaletest/add-shared-labels.go
test/e2e/framework/scaletest/add-unique-labels.go
test/e2e/framework/scaletest/create-network-policies.go
test/e2e/framework/scaletest/create-resources.go
test/e2e/framework/scaletest/delete-and-re-add-labels.go
test/e2e/framework/scaletest/get-publish-metrics.go
test/e2e/framework/scaletest/options.go
test/e2e/framework/scaletest/validate-nodes.go
test/e2e/framework/types/runner.go
test/e2e/jobs/scale.go
test/e2e/scale_test.go

Create automation workflow to run scale test automatically. Initially to keep it simpler, it will be executed daily with latest commit from main. In future it can be changed to run at merge if desired.
Current Scale test configuration is 1000 deployments of 20 replicas of kapinger pods running on a cluster of 1000 nodes. The cluster will be created and deleted at each automatic execution.
Changes in this PR:
* Creation of workflow for daily execution
* Add code to create Scale Test cluster
* Simplify environment variables handling by doing it in `params` package 
* Update kapinger version
* Update kapinger memory limit
* Update context handling in scale test steps (improve flakiness of test)
* Notify test job's root ctx of os signals (SIGINT and SIGTERM) to allow proper cleanup in case of …

test: automate scale test execution

---

.github/workflows/images.yaml

Fix typo in workflow file: `AZURE_APP_INSIGHTS_ID` -> `AZURE_APP_INSIGHTS_KEY`
---

fix(test): fix typo in var name

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md
docs/03-Metrics/plugins/Linux/dns.md

This PR fixes broken links to the contributing guide and other `retina.sh/docs` pages. 
Resolves #1333
N/A
I also adjusted some working links to `retina.sh/docs` to avoid a brief "Page Not Found" flash before loading.
---

docs: fix broken links to `retina.sh/docs`

---

test/e2e/jobs/perf.go
test/e2e/scenarios/perf/get-perf-regression-results.go
test/e2e/scenarios/perf/publish-perf-results.go

This pull request involves renaming variables and types related to performance testing to improve clarity and consistency. The changes primarily focus on replacing the term "regression" with "delta" and "benchmark" with "baseline" across various files and functions.
Key changes include:
* [`test/e2e/jobs/perf.go`](diffhunk://#diff-4569b363dc867f6945f817268ae7e84f1f8918a68111f37521a99bac771e39bfL16-R23): Renamed `benchmarkFile` to `baselineFile` and `regressionFile` to `deltaFile`. Updated corresponding references in the `RunPerfTest` function. [[1]](diffhunk://#diff-4569b363dc867f6945f817268ae7e84f1f8918a68111f37521a99bac771e39bfL16-R23) [[2]](diffhunk://#diff-4569b363dc867f6945f817268ae7e84f1f8918a68111f37521a99bac771e39bfL57-R66)
* …

refactor: rename regression to delta and benchmark to baseline for perf-tests

---

docs/07-Consuming Tools/vscode.md

The recent addition to our docs by #1326 introduced a title without a space, this PR fixes that.
N/A
Before/Current
New
---

fix(docs): Fix lack of space in title

---

.golangci.yaml

After [deps: bump github.com/golangci/golangci-lint from 1.64.2 to 1.64.5 in /hack/tools](https://github.com/microsoft/retina/commit/f4d8f1610a54dc282282cdd3ac14c7f1291388c0), all PR started failing the golangci-lint workflow.
This PR removes a parameter that has been deprecated by golanci-lint.
No issue created.
See workflow below.
Syntax updated as per golang-lint documentation
https://golangci-lint.run/usage/linters/#govet
https://github.com/golangci/golangci-lint/blob/a8b68a590a88bbde93b27f8bf02031cb1db78b2b/pkg/config/loader.go#L402-L407
---

fix(lint-ci): Removing golang-lint govet deprecated parameter

---

.github/workflows/release-validation.yaml

Add workflow to validate retina release. This workflow is dependent on successful run of images and helm release workflows. The job includes steps which validate the following:
1. All retina images can be pulled
2. Helm chart can be pulled
3. `kubectl krew install retina` works
4.  go package version exist
* I have tested the workflow dependency in my own fork
* I have tested every job step in my own fork using latest tag v0.0.26
---

test(release): Add release validation workflow

---

.github/workflows/release-validation.yaml

* Use array format to define workflow names for readability
* Enclose in double-quotes to prevent trailing space issues
* Fix docker pull, simplify step and just pull images
* Fix krew index step, export PATH after krew installation
* Fix issue with TAG in go package version check
* Related to PR https://github.com/microsoft/retina/pull/1380
Test on upstream `test-sr` branch
Link to job run: https://github.com/microsoft/retina/actions/runs/13548239168/job/37865147112
---

test(release): Fix workflow for release validation.

---

.github/workflows/commit-message.yaml

Ubuntu 20.04 LTS runner will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101
---

fix(workflow): update github workflow runner due to deprecation of image

---

deploy/grafana-dashboards/hubble-dns.json

Fix query to remove `ips_returned!="0"` which only included responses that did return at least 1 IP - this resulted in no DNS errors showing in the table
With filter
Without filter
---

fix(grafana): Fix Hubble DNS dash for Response Table query

---

cli/cmd/capture/create.go

Added nil check for S3 storage properties so that the retina cli doesn't throw nil pointer error when azure blob storage is used instead of S3 storage.
This PR addresses issue https://github.com/microsoft/retina/issues/1425
---

fix(retina capture): bug fix for nil pointer error

---

test/e2e/scenarios/perf/get-network-performance-measures.go

This pull request includes a small change to the `test/e2e/scenarios/perf/get-network-performance-measures.go` file. The change updates the Docker image version used in the `Run` method from `v20241002` to `v20250402` to ensure the latest version is utilized for network performance tests.
* [`test/e2e/scenarios/perf/get-network-performance-measures.go`](diffhunk://#diff-552021fa11b21d2818ffec68ed586178c09389024331b93f0425b6218c068be8L24-R24): Updated the Docker image version in the `Run` method from `v20241002` to `v20250402`.
Add any additional notes or …

deps: update network performance test image version to v20250402

---

cmd/hubble/daemon_main_linux.go
operator/cmd/cilium-crds/zap_linux.go

After setting logLevel: debug in the ConfigMap, some agent loggers are still on info level.
This is not consistent. For instance, this logger DOES correctly use debug level
level=debug caller=packetparser/packetparser_linux.go
whereas components like payload parser will NOT ever send debug logs.
This PR sets the logrus logLevel according to the global log level.
https://github.com/microsoft/retina/issues/597
---

fix(log): set logrus logLevel according to the global log level

---

.github/workflows/images.yaml
.github/workflows/perf-manual.yaml
.github/workflows/perf-schedule.yaml
.github/workflows/perf-template.yaml

The workflow was failing after templating it as workflow call cannot process runtime variables. We need to pass in the secrets through the workflow as variables.
---

fix(perf-workflow): add secrets to the template

---

go.mod
go.sum

This pull request updates the dependency version for `github.com/cilium/cilium` in the `go.mod` file. The version has been incremented from `v1.18.0-pre.0.0.20250331121417-b4508ebd8be7` to `v1.18.0-pre.1`.
Dependency update:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L280-R280): Updated `github.com/cilium/cilium` to `v1.18.0-pre.1` to align with the latest pre-release version.
---
Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) …

deps: bump cilium to v1.18.0-pre.1

---

test/e2e/framework/azure/create-cluster-with-npm.go

We have distro-dependent eBPF code that needs ongoing validation.

test: enable Mariner pool for E2E

---

pkg/plugin/conntrack/_cprog/conntrack.c
pkg/plugin/conntrack/_cprog/conntrack.h

Before, conntrack will immediately delete a connection from its map whenever we see the `FIN` flag, which is problematic for connections that got closed from server-side. This PR fixes that by take into account the 4-way teardown process. Also refactored some code to make it more readable.
Closes #1417
Verified with kapinger that the issue no longer appears
```bash
Mar 14 22:08:47.238: kapinger-good-65454cb695-kglv4:49474 (ID:40841) -> kapinger-good-65454cb695-nh72g:8080 (ID:40841) to-endpoint FORWARDED (TCP Flags: SYN:true)
Mar 14 22:08:47.238: kapinger-good-65454cb695-kglv4:49474 (ID:40841) <- kapinger-good-65454cb695-nh72g:8080 (ID:40841) to-stack FORWARDED (TCP Flags: SYN:true  ACK:true)
Mar 14 22:08:47.239: kapinger-good-65454cb695-kglv4:49474 (ID:40841) -> …
```

fix(conntrack): remove closing tcp connections from conntrack gracefully

---

deploy/standard/manifests/controller/helm/retina/templates/daemonset.yaml
deploy/standard/manifests/controller/helm/retina/templates/operator.yaml
deploy/standard/manifests/controller/helm/retina/values.yaml

Adds missing `imagePullSecrets` and affinity/tolerations support to the legacy chart.
Maintains backwards compatibility with the exsting chart.
`helm template` of old and new charts with default values, no diff in generated manifests.
Provided `imagePullSecrets` and `tolerations`/`affinity` blocks to values and they render as expected.
None
---

feat: add imagePullSecrets and affinity/tolerations support to the standard chart

---

shell/Dockerfile

As title. Resolved a couple of CVEs
Before
After
---

chore: bump retina shell base image

---

controller/Dockerfile.windows-native

Adds a line to the Windows native Dockerfile to mark the Retina directory as safe.
N/A
- [] I have added tests, if applicable.

chore: Mark retina directory as safe in windows Dockerfile

---

pkg/k8s/apiserver_linux.go
pkg/watchers/apiserver/apiserver.go
pkg/watchers/apiserver/apiserver_test.go

In some cases the flows incorrectly assumed APIServer IPs as world.
This PR adds functionality to the watcher to extract IPs from the Kubernetes service and endpoints. In some managed Kubernetes offerings these IPs are used to establish connections from and to the kube-apiserver.
Before:
After:
---

feat: additional apiserver IPs from service and endpoint

---

deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml

Fixes https://github.com/microsoft/retina/pull/1458
In the PR above, I only added the `/etc/host-os-release` volumeMount in 
`deploy/standard/manifests/controller/helm/retina/templates/daemonset.yaml`
but not in 
`deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml`
The omission was because in the former we iterate over the volume mount list defined in values.yaml, while the latter defines them explicitly in the daemonset.

fix: include Mariner check for Hubble scenario

---

deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml
deploy/hubble/manifests/controller/helm/retina/values.yaml

- In certain cases, cluster admins must be able to directly modify resources.requests to bypass pending issues with the retina-agent DaemonSet.
- Recommit 90a370f20b5c20c360caa7e70bd0572f9cb2c79a due to gpg-signing PR #1589 (Requested by @nddq)
Reopen from #1589
---

feat(helm): Add resources.requests for retina-agent

---

deploy/hubble/manifests/controller/helm/retina/templates/_helpers.tpl

Fix ingress helm template issue due to missing helper script:
- The hubble-ui subchart of retina doesn't include the `ingress.paths` definition from the cilium chart, so it needs to be defined instead in the _helpers.tpl helper script of retina.
- Root cause line in `ingress.yaml` template:
https://github.com/microsoft/retina/blob/7e2fc3346eaabf3ece23c1d181a1de7dcac2bd82/deploy/hubble/manifests/controller/helm/retina/templates/hubble-ui/ingress.yaml#L38
- https://github.com/cilium/cilium/pull/13682
Ingress completly created (screenshot from k9s):
N/A
---

fix(helm): Missing helper template for ingress resource

---

test/e2e/framework/azure/create-cluster-with-npm.go

Currently Retina is not FIPS-compliant across the board. This is to help validate the support matrix.

test: add FIPS-enabled Mariner node pool to E2E

---

test/e2e/framework/azure/create-cluster-with-npm.go

Reverting #1602 that added a stale OSSKU tag which is failing in merge queue now.
This was merged due to a GH a race condition in a skipped job.
Will follow-up with another PR just enabling FIPS on the existing AzureLinux node pool.

fix: revert: test: add FIPS-enabled Mariner node pool to E2E

---

test/e2e/framework/azure/create-cluster-with-npm.go

#1602 used a stale SKU tag, and somehow slipped through the CI.
Submitting this again with the up-to-date AzureLinux tag.

test: Enable FIPS using existing AzureLinux node pool.

---

deploy/hubble/manifests/controller/helm/retina/values.yaml
deploy/standard/manifests/controller/helm/retina/values.yaml

When running on the FIPS-compliant Ubuntu 20.04, Retina requires `SYS_RESOURCE` on top of `IPC_LOCK`.
Also, skip attaching to unavailable kernel hook points.
Merge after https://github.com/microsoft/retina/pull/1601 - otherwise the pod still fails, just at a later stage.

fix(fips): Grant permissions to support FIPS on Ubuntu

---

pkg/plugin/dropreason/dropreason_linux.go
pkg/plugin/dropreason/dropreason_linux_test.go
pkg/plugin/dropreason/ebpfsetup_linux.go
pkg/plugin/dropreason/types_linux.go

In #1458 I added a kernel version check to only attach `fexit` programs when they're supported.
We also need to ensure we don't even load them into the kernel.

fix(DropReason): Do not load fexit programs on kernels below 5.5

---

.github/workflows/release-images.yaml
Makefile

This PR is a follow up from: https://github.com/microsoft/retina/pull/1538/files#diff-fb3f33cdd2a5865385222d244e9bdc9a7ebee2756d506f6495f83a5cff42b25a
The ARM64 Operator image was added to the test workflow, and the ADO (Microsoft internal release) pipeline, but not to GHCR release flow. This PR fixes that.
https://github.com/microsoft/retina/issues/1582
This flow was tested here: https://github.com/microsoft/retina/actions/runs/15065640778/job/42350022052
---

fix(image): Adding ARM64 Operator image release

---

.github/workflows/images.yaml

Our E2e job is getting skipped in the merge queue, because of YAML parsing errors.
We have invalid syntax in the if-statements checking for success of prerequisite jobs that need to run for `manifests` and `E2E` to run. 
Looks like this used to be ignored and those jobs just ran, while recently Github started enforcing stricter YAML syntax validation which is causing these jobs to get skipped! 
It started about a week ago, example errors at the bottom of the page:
https://github.com/microsoft/retina/actions/runs/14842770818

fix: e2e job skipped due to yaml syntax error

---

deploy/standard/manifests/controller/helm/retina/templates/rbac.yaml

Adds RBAC to allow querying `endpoints` in the standard chart.
Fixes errors introduced by https://github.com/microsoft/retina/pull/1573 for failures to query for `endpoints` when the legacy control plane is deployed.
Deployed with new version of the chart, no longer receive errors like
```
retina ts=2025-05-20T20:23:52.758Z level=error caller=apiserver/apiserver.go:120 msg="failed to initialize new cache" error="failed to retrieve ips from kubernetes endpoint: retrieving kubernetes endpoint: endpoints \"kubernetes\" is forbidden
retina ts=2025-05-20T20:23:52.758Z level=error caller=watchermanager/watchermanager.go:76 msg="refresh failed" error="failed to retrieve ips from kubernetes endpoint: retrieving kubernetes endpoint: endpoints \"kubernetes\" is forbidden
```
---
Please refer to the …

fix: Allow RBAC for endpoints to the standard chart

---

pkg/plugin/ciliumeventobserver/parser_linux.go

This warning is being logged to many times.
---

chore(ciliumeventobserver): Remove warn for messageType not supported

---

pkg/common/endpoint.go
pkg/controllers/cache/cache.go

In this hot code path computing the key for the debug log does a bunch of unnecessary string  allocations.
Refactor to use `zap` lazy serialization so we only incur this cost when debug logging is turned on.
Deployed with debug logging turned on, logs as expected.
```
retina-agent-q9525 retina ts=2025-05-22T22:50:39.044Z level=debug caller=cache/cache.go:100 msg="pod found for IP" ip=172.26.11.226 pod=platform/thanos-rule-remote-1
retina-agent-q9525 retina ts=2025-05-22T22:50:39.044Z level=debug caller=cache/cache.go:140 msg="pod found for IP" ip=172.26.11.226 pod=platform/thanos-rule-remote-1
retina-agent-q9525 retina ts=2025-05-22T22:50:39.044Z level=debug caller=cache/cache.go:94 msg="pod not found for IP" ip=172.27.12.108
retina-agent-q9525 retina ts=2025-05-22T22:50:39.044Z …
```

fix: Remove unnecessary allocations from debug log

---

deploy/standard/manifests/controller/helm/retina/templates/daemonset.yaml
deploy/standard/manifests/controller/helm/retina/values.yaml

Allows passing arbitrary environment variables to the DaemonSet in the standard Helm chart.
No diff between `helm template` with current chart with default values and that from this PR.
Diff with provided `env` values shows values added as expected.
```
env:
- name: test1
value: test1
- name: test2
value: test2
- name: POD_NAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: metadata.name
- name: NODE_NAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: spec.nodeName
```
---

feat(helm): Allow passing arbitrary env variables to the DaemonSet

---

deploy/hubble/manifests/controller/helm/retina/templates/agent/clusterrole.yaml

Prevent this issue when running on Cilium CNI and no operator enabled
```
ts=2025-05-30T08:34:19.360Z level=warn caller=logrus-zap-hook@v0.1.0/zap.go:51 msg="pkg/mod/k8s.io/client-go@v0.32.4/tools/cache/reflector.go:251: failed to list *v2.CiliumEndpoint: ciliumendpoints.cilium.io is forbidden: User \"system:serviceaccount:kube-system:retina-agent\" cannot list resource \"ciliumendpoints\" in API group \"cilium.io\" at the cluster scope" subsys=klog
ts=2025-05-30T08:34:19.360Z level=error caller=k8s/watcher_linux.go:51 msg="Error watching k8s resource" subsys=k8s-watcher resource=v2.CiliumEndpoint underlyingError="pkg/mod/k8s.io/client-go@v0.32.4/tools/cache/reflector.go:251: Failed to watch *v2.CiliumEndpoint: …
```

chore(agent): Allow agent to watch endpoints on Hubble CP

---

docs/08-Contributing/02-development.md

Removing duplicate docs from the Development page, which are already present on the Overview.
NA
- [] I have added tests, if applicable.
---

docs: Remove duplicate docs

---

pkg/plugin/linuxutil/ethtool_handle_linux.go
pkg/plugin/linuxutil/ethtool_stats_linux.go
pkg/plugin/linuxutil/ethtool_stats_linux_test.go
pkg/plugin/linuxutil/linuxutil_linux.go
pkg/plugin/linuxutil/linuxutil_mock_generated_linux.go
pkg/plugin/linuxutil/types_linux.go

This pull request updates the `ethtool` dependency to version `v0.6.1` and introduces significant changes to the `EthtoolInterface` implementation and related code. The most notable updates include replacing the `Stats` method with `StatsWithBuffer`, modifying constructors and functions to handle additional buffer parameters, and updating tests accordingly.
* Updated `ethtool` dependency from version `v0.6.0` to `v0.6.1` in `go.mod`.
* Replaced the `Stats` method with `StatsWithBuffer`, which accepts additional buffer parameters (`gstring` and `stats`) for improved handling of interface statistics. [[1]](diffhunk://#diff-07973045315381e9cfea6512cdcb566c022108b90e3df891715422ca3598735cL29-R36) [[2]](diffhunk://#diff-ab186a8a488c84ccab2df9bfed9f5c0412cf4c45ff62c184a7b661e0873add61L109-R110) …

feat: update ethtool dependency and modify Stats method to use buffer

---

shell/Dockerfile

Retina Shell Image Build is failing due to failure to install `aznfs` package which is a new dependency of `conntrack` package added recently for some reason. Previous successful pipeline execution did not show that in the list of packages being installed: https://github.com/microsoft/retina/actions/runs/15496126524/job/43634783255
First failed pipeline execution with the problem: https://github.com/microsoft/retina/actions/runs/15530534142/job/43721335257
This PR adds `--exclude=aznfs` to the `tdnf install` command in the `shell/Dockerfile` to exclude the `aznfs` package from the list of installed packages as a workaround.
There's an issue created about it in azurelinux repository: https://github.com/microsoft/azurelinux/issues/13971
References below:
If this pull request is related to …

fix: exclude aznfs package from installed packages list

---

shell/Dockerfile

Reverts microsoft/retina#1667
It was a workaround for an issue that was fixed: https://github.com/microsoft/azurelinux/issues/13971#issuecomment-2956384627

fix: revert: exclude aznfs package from installed packages list

---

Makefile
shell/Dockerfile
shell/README.md

Add eBPF-based [pwru](https://github.com/cilium/pwru) executable binary to retina-shell for tracing network packets in the Linux kernel with advanced filtering capabilities
#1662 
I have tested by building the image in isolation 
```sh
docker buildx build \
--platform linux/amd64,linux/arm64 \
--build-arg GOARCH=amd64 \
-t ghcr.io/srodi/retina/retina-shell \
--push .
```
And run on both linux/amd64 and linux/arm64
```sh
❯ docker run --rm -it ghcr.io/srodi/retina/retina-shell \
pwru --version
Unable to find image 'ghcr.io/srodi/retina/retina-shell:latest' locally
latest: Pulling from srodi/retina/retina-shell
67f02795c36b: Pull complete 
879a565e8972: Pull complete 
b825e06ce1fe: Pull complete 
Digest: sha256:24877a745d4fa6f0ab5b5cb17399e13b8b764961658be53676e8749cb2f7525c
Status: …
```

chore(shell): Add pwru binary to retina-shell

---

Makefile
cli/Dockerfile
internal/buildinfo/buildinfo.go
pkg/capture/constants/job_specification.go

When a retina capture is created by retina-kubectl CLI, it uses `ghcr.io/microsoft` as registry to pull retina agent image from. This change allows setting at build time what image name should CLI use when creating retina capture jobs.
Logs of tests executed:
```bash
$ make kubectl-retina-image
echo "Building for linux/amd64"
Building for linux/amd64
set -e ; \
make container-docker \
PLATFORM=linux/amd64 \
DOCKERFILE=cli/Dockerfile \
REGISTRY=ghcr.io \
IMAGE=microsoft/retina/kubectl-retina \
VERSION=v0.0.34-16-gf04641c \
TAG=v0.0.34-16-gf04641c-linux-amd64 \
CONTEXT_DIR=/home/lx/projects/retina/repositories/official-retina \ …
```

chore(cli): set retina agent image registry at build time

---

.github/workflows/goreleaser.yaml

Goreleaser job had an issue introduced in https://github.com/microsoft/retina/pull/1695
---

fix: Goreleaser job

---

cli/Dockerfile
controller/Dockerfile
controller/Dockerfile.gogen
controller/Dockerfile.proto
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
controller/Dockerfile.windows-cgo
controller/Dockerfile.windows-native
go.mod
go.sum
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022
shell/Dockerfile
test/image/Dockerfile

Moving to azurelinux 3.0 for base and build images as mariner 2.0 is being deprecated. Also bumping to go v1.24.3
---

deps(build): bump base and build images to azure linux 3.0

---

cli/cmd/capture/capture.go
cli/cmd/capture/create.go
cli/cmd/capture/create_test.go
cli/cmd/capture/delete.go
cli/cmd/capture/delete_test.go
cli/cmd/capture/download.go
cli/cmd/capture/list.go
cli/cmd/capture/table_util.go
cli/main.go

kubectl-retina CLI does not have e2e tests to validate its behavior. For that, some refactoring is needed.
This PR:
* refactors CLI code to allow injection of fake kubeclient for testing purposes. This allows the creation of tests that can validate that kubernetes resources are created as expected.
* Add some tests for `capture create` and `capture delete` commands to confirm that main arguments are behaving as expected.
Other tests will be added in the future and this code will be a reference for that.
Add any additional notes or context about the pull …

chore(cli): refactor CLI to allow better testing interface + add tests

---

Makefile
controller/Dockerfile.windows-retina-oss-build

We want to separate the windows build into 2 steps
1. Build the binaries needed for the final image
2. Build the final image including the binaries built in step 1
For step 1, add a build-binaries task to the Makefile that builds the binaries needed for the final image.
For step 2, add a Dockerfile for the windows build that builds the final image including the binaries built in step 1
---

refactor: add dockerfile for windows build and make build-binaries

---

deploy/hubble/manifests/controller/helm/retina/templates/hubble-relay/service.yaml
deploy/hubble/manifests/controller/helm/retina/templates/hubble-ui/service.yaml
deploy/hubble/manifests/controller/helm/retina/values.yaml

Add [trafficDistribution](https://kubernetes.io/docs/concepts/services-networking/service/#traffic-distribution) field support to Hubble services (excluding DaemonSet-connected services) with Kubernetes version compatibility check (≥1.31). This provides better performance and reliability than annotation-based [topologyAwareRouting](https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/) by being natively integrated into the Service API.
- Added trafficDistribution configuration to Hubble Relay and UI services in values.yaml
- Updated service templates with conditional rendering based on Kubernetes version
- Excluded DaemonSet-connected services (agent, peer) as they use hostNetwork
Retina administrators can now set hubble.relay.service.trafficDistribution: …

feat(hubble): Add `trafficDistribution` field support for Kubernetes 1.31+

---

.github/workflows/e2e-test-event-writer.yml
controller/Dockerfile
controller/Dockerfile.windows-native
pkg/plugin/ebpfwindows/ebpf_windows.go
pkg/plugin/ebpfwindows/ebpf_windows_test.go
pkg/plugin/ebpfwindows/metricsmap_windows.go
test/e2e/scenarios/windows/validate-winbpf-metrics.go
test/e2e/tools/event-writer/bpf_event_writer.c
test/e2e/tools/event-writer/event_writer.cpp
test/e2e/tools/event-writer/event_writer.h
test/e2e/yaml/windows/install-ebpf-xdp.yaml
test/e2e/yaml/windows/non-hpc-pod.yaml

- Updates RetinaEbpfApi version
- Updates processing of Metrics Map due to API changes
- Adds processing for lost events API
- Updates tests to utilize added windows_metrics map
---

Consume latest RetinaEbpfApi; Add lost events API; Update struct processing due to latest RetinaEbpfApi changes

---

pkg/controllers/daemon/nodereconciler/cell_linux.go
pkg/controllers/daemon/nodereconciler/node_controller_linux.go

Add predicates to filter out node events that are not important for Retina agent.
Fixed https://github.com/microsoft/retina/issues/1453
---

fix: node watcher should only reconcile on important events

---

.github/workflows/e2e-test-event-writer.yml

e2e-test-event-writer.yml was not triggering on dev branches
n/a
n/a
n/a
---

Update e2e-test-event-writer yml to trigger on dev branch

---

shell/Dockerfile
shell/README.md
shell/manifests.go
shell/manifests_test.go

Add inspektor gadget to retina shell.
Changes:
* Add script to run before bash at creation of pod to mount `debugfs`
* Install IG + configure `HOST_ROOT` environment variable
* Mount Volume `/run` from host for IG to access runtime data
```bash
..
root@aks-nodepool1-42816995-vmss000001 [ / ]# ig run top_tcp:latest | head
RUNTIME.CONTAINERNAME                       PID              TID SRC                                      DST                                      COMM                   SENT   RECEIVED
RUNTIME.CONTAINERNAME                       PID              TID SRC                                      DST …
```

chore(cli): add inspektor gadget to retina shell

---

cli/Dockerfile
controller/Dockerfile
controller/Dockerfile.gogen
controller/Dockerfile.proto
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
controller/Dockerfile.windows-cgo
controller/Dockerfile.windows-native
controller/Dockerfile.windows-retina-oss-build
hack/tools/kapinger/Dockerfile
hack/tools/toolbox/Dockerfile
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022
test/image/Dockerfile

#1791 Indicated presence of some CVE's in agent & operator images.
Bumping golang base image to address some of them.
Some CVE's still coming from `tdnf` installed tools in agent Dockerfile.
#1791
Operator all CVE's resolved
Agent CVE's not resolved yet
---

fix(cve): Upgrading base golang image to fix CVE's

---

Makefile
deploy/standard/manifests/controller/helm/retina/templates/configmap.yaml

- Disable operator installation for `localCtx` (not needed)
- Windows configmap is missing `enableAnnotations` config
```bash
$ kg cm retina-config-win -oyaml 
apiVersion: v1
data:
config.yaml: "apiServer:\n  host: 0.0.0.0\n  port: 10093\nlogLevel: info\nenabledPlugin:
[\"hnsstats\"]\nmetricsInterval: \nmetricsIntervalDuration: 10s\nenableTelemetry:
false\nenablePodLevel: true\nremoteContext: false\nenableAnnotations: true\ntelemetryInterval:
15m"
kind: ConfigMap
...
```
```bash
$  kg po -A -owide | grep -i retina    
kube-system         retina-agent-d47xk                                   1/1     Running   0 …
```

fix(localctx+win): Fix the helm insatll command for localCtx

---

Makefile
deploy/standard/manifests/controller/helm/retina/templates/configmap.yaml

Cherry picking following fix from main branch: fix(localctx+win): Fix the helm insatll command for localCtx (https://github.com/microsoft/retina/pull/1807)
- Disable operator installation for `localCtx` (not needed)
- Windows configmap is missing `enableAnnotations` config
---

Cherry picking locactx fix form main branch

---

test/e2e/framework/azure/create-cluster.go
test/e2e/framework/azure/create-publicip.go
test/e2e/jobs/scale.go

Run E2e Tests pipeline is failing during cluster creation with the following error:
```bash
#################### CreateNPMCluster ###################################################################
2025/08/14 18:58:11 when the cluster is ready, use the below command to access and debug
2025/08/14 18:58:11 az aks get-credentials --resource-group runner-e2e-netobs-1755197881 --name runner-e2e-netobs-1755197881 --subscription ***
2025/08/14 18:58:11 creating cluster "runner-e2e-netobs-1755197881" in resource group "runner-e2e-netobs-1755197881"...
2025/08/14 18:58:40 failed to create cluster: GET https://management.azure.com/subscriptions/***/providers/Microsoft.ContainerService/locations/eastus2/operations/fd882d18-319b-4200-aa9e-a2934886e35b …
```

 [SFI - Service Tags] Retina Virtual Tags

---

docs/06-Troubleshooting/shell.md
shell/Dockerfile

chore(shell): Add mpstat and doc
