microsoft/retina

.github/workflows/images.yaml
Makefile

Forked PRs can't push to upstream GHCR, remove push steps (and default to `--load`).

fix: remove push images

---

.github/workflows/release-images.yaml

Publishes images from main and tags

feat: release images from main and tags

---

.pipelines/cg-pipeline.yaml

chore: adding a new pipeline in ADO for component governance

---

deploy/manifests/controller/helm/retina/templates/daemonset.yaml
deploy/manifests/controller/helm/retina/values.yaml

Add support for nodeSelector and tolerations override in helm chart.

feat(helm): customize nodeselector and tolerations

---

.github/workflows/integration.yaml

Merge queue test

---

.github/workflows/codeql.yaml

fix: remove check on codeQL job level.

---

pkg/plugin/filter/filter_map_linux.go

fixes: #153 
1. Built amd64 image and deployed them in a K8s cluster
2. agent pod is up and running

fix: failed to initialize filter map

---

CONTRIBUTING.md

This updates CONTRIBUTING to include information about commit signing and the DCO.
Fixes #197

fix: Update CONTRIBUTING

---

.github/pull_request_template.md
docs/contributing/readme.md
docs/installation/setup.md

Quick Install guide: 1) include required Helm version and 2) remove reference to `make` commands.
PR template: link docs for signing commits.

docs: clarifications in quick install guide, plus instructions for commit sign-off

---

controller/Dockerfile.controller
controller/Dockerfile.gogen
controller/Dockerfile.proto
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
go.mod
hack/tools/go.mod
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022
test/image/Dockerfile
test/integration/Dockerfile.integration

chore: update to go 1.22

---

.github/workflows/images.yaml
test/e2e/framework/azure/create-cluster-with-npm.go
test/e2e/framework/azure/create-cluster.go
test/e2e/scenarios/retina/retina_scenarios_test.go

fix: unconstrain e2e AZ

---

deploy/grafana/dashboards/simplify-grafana-overwrite_test.go
deploy/grafana/dashboards/simplify-grafana_test.go
pkg/capture/outputlocation/blob.go

Updated ioutil to os
Issue #352 
---

fix: Updated from ioutil to os

---

.github/workflows/e2e.yaml
.github/workflows/images.yaml

Moves the Azure/login GHA authentication to the more secure OIDC mechanism.

feat: migrate azure/login gha to oidc

---

.github/workflows/images.yaml
Makefile

fix: make command for windows builds not working correctly

---

.github/workflows/goreleaser.yaml

Update condition so this will only run in owner's repo
---

chore: update krew release bot condition

---

.github/workflows/release-images.yaml

fix: windows builds in release pipeline

---

docs/contributing/developing.md

Provent a pitfall when developing on Retina for the first time.

docs(development): caveat about checking llvm installation

---

.github/workflows/test.yaml
.github/workflows/trivy.yaml

chore: bump actions/checkout from v3 to v4 in test and trivy

---

test/e2e/framework/azure/create-cluster-with-npm.go

fix: add node OS upgrade channel for e2e cluster creation

---

controller/Dockerfile
controller/Dockerfile.gogen
controller/Dockerfile.proto
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
controller/Dockerfile.windows-cgo
controller/Dockerfile.windows-native
go.mod
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022
test/image/Dockerfile

chore: update Go image used in Dockerfiles to 1.22.4

---

controller/Dockerfile
operator/Dockerfile

chore: bump hubble version + use mariner distroless image for operator

---

Makefile

chore: bump hubble version in Makefile

---

deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml

fix: delete duplicate node selector

---

README.md
deploy/legacy/manifests/controller/helm/retina/templates/daemonset.yaml

Fixes chart syntax for IB mounts

fix: ib chart mounts and update docs

---

pkg/module/metrics/metrics_module.go
pkg/module/metrics/metrics_module_test.go

fix: remove namespace from Module.includedNamespaces

---

deploy/legacy/manifests/controller/helm/retina/templates/podmonitor.yaml
deploy/legacy/manifests/controller/helm/retina/templates/servicemonitor.yaml
deploy/legacy/manifests/controller/helm/retina/values.yaml

Adding support for `ServiceMonitor`.

feat(helm): Add ServiceMonitor

---

deploy/legacy/grafana/dashboards/clusters.json
deploy/legacy/grafana/dashboards/dns.json
deploy/legacy/grafana/dashboards/pod-level.json

This PR is to fix https://github.com/microsoft/retina/pull/158
* reduce scope of PR
* [make it possible to select multiple nodes on clusters dash](https://github.com/microsoft/retina/pull/158#discussion_r1668847543)
* [fix pod-level regex](https://github.com/microsoft/retina/pull/158#discussion_r1589821558)
* [~~use named capture groups here to separate displayed value and used value in clusters dash~~](https://github.com/microsoft/retina/pull/158#discussion_r1680522494)
>NOTE: I have reverted the change to DS_PROMETHEUS not to break existing deployments and tests. This was requested in [this comment](https://github.com/microsoft/retina/pull/158#pullrequestreview-2226013402)
fix https://github.com/microsoft/retina/issues/271
If this pull request is related to any issue, please mention it …

fix(grafana/PR#158): fix node selection, metrics name dns, pod-level dash

---

docs/02-Installation/01-Setup.md

Page reference link was broken
#809 
---

fix(docs): update broken link for prometheus and grafana pages

---

pkg/plugin/windows/pktmon/pktmon_plugin_windows.go

the grpc windows client is pretty noisy with random grpc connection errors
we currently log them and emit them, since (during test) they don't impact the full functionality of the stream. However, this specific error
is indicative that the pktmon-server.exe has died for some reason. Currently, if the goroutine that kicked off the server exits, the main thread will keep trying to dial the server. This change is to return in the main thread if the goroutine exits, by writing to the error channel
in that case retina windows will restart and setup all of the pktmon bits again
Please add any relevant screenshots or GIFs to showcase …

fix: restart if pktmon server closes

---

pkg/telemetry/perf_unix.go
pkg/telemetry/telemetry.go

Additionally properties for tracking retina memory pressure
---

fix: add heap and gc memory stats

---

.github/workflows/kapinger.yaml

Fix typo in kapinger pipeline script
N/A
---

fix(pipeline): Fix typo in kapinger pipeline script

---

pkg/managers/pluginmanager/pluginmanager.go
pkg/plugin/dropreason/dropreason_linux.go
pkg/plugin/packetforward/packetforward_linux.go

Enhance error handling by wrapping errors with additional context during plugin operations and eBPF compilation.

feat: add extra context to errors

---

site/package-lock.json
site/package.json

As title
Verified with `make docs-prod`
---

chore(deps): bump docusaurus to 3.6.1 in /site

---

go.mod

Add retract directive for v0.10.0, which was published accidentally.
Closes #714 
---

fix: add retract directive for v0.10.0

---

.github/workflows/scale-test.yaml

* Create a new GitHub Workflow to run scale test. 
* The new workflow can be executed manually or reused by other workflow.
---

test: create pipeline to run scale test

---

.github/workflows/images.yaml
.github/workflows/perf.yaml

This pull request introduces a new job for performance testing and modifies the existing workflow for network performance measurement. The main changes include adding a new performance test job to the `images.yaml` workflow and updating the `perf.yaml` workflow to streamline its execution.
New performance test job:
* [`.github/workflows/images.yaml`](diffhunk://#diff-d0a3d6684c78a148cbf0725d5fe8b5aab6431da05b698a82c9e015516f3020baR334-R366): Added a new job `perf` to run Retina Performance Tests after the `manifests` job completes successfully. This job includes steps for checking out the code, setting up Go, logging into Azure CLI, and running end-to-end tests with performance tags.
Updates to network performance measurement workflow:
* …

feat: add performance testing workflow for PR workflow

---

deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml
deploy/hubble/manifests/controller/helm/retina/templates/operator/deployment.yaml
deploy/hubble/manifests/controller/helm/retina/values.yaml

This pull request adds a list called `tolerations` to the operator and agent sections of the values file, and implement them into the templates.
This is a pull request to close #1112, as agreed upon in the Office Hours meeting, Friday the 6th.
---

feat: add tolerations to values and templates

---

Makefile
cli/Dockerfile
controller/Dockerfile
controller/Dockerfile.gogen
controller/Dockerfile.proto
controller/Dockerfile.windows-2022
controller/Dockerfile.windows-cgo
controller/Dockerfile.windows-native
operator/Dockerfile
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022
test/image/Dockerfile

Upgrade go stdlib version to fix vulnerabilities.
CVE no longer present, only from hubble. 
---

fix(version-upgrade): Update go std lib from v1.23.4  -> 1.23.5

---

docs/06-Troubleshooting/shell.md

azlinux3 now uses iptables-nft by default, so update the documentation to reflect that.
N/A
N/A
N/A
---

docs: update note about retina-shell and iptables

---

test/multicloud/test/integration/retina_gke_test.go

test(mc-gke): Uncomment GKE test for retina error logs check

---

.github/workflows/daily-scale-test.yaml
test/e2e/framework/kubernetes/install-retina-helm.go
test/e2e/jobs/jobs.go
test/e2e/scale_test.go

Enable heartbeat in scale test.
#1040 
---

test: enable heartbeat in scale test

---

deploy/hubble/prometheus/values.yaml
test/multicloud/Makefile
test/multicloud/README.md
test/multicloud/live/files/mc-demo-eks-coredns-custom.yaml
test/multicloud/live/retina-aks/outputs.tf
test/multicloud/live/retina-eks/main.tf
test/multicloud/live/retina-eks/outputs.tf
test/multicloud/live/retina-gke/outputs.tf
test/multicloud/modules/aks/outputs.tf
test/multicloud/modules/eks/outputs.tf
test/multicloud/modules/gke/output.tf
test/multicloud/modules/kind/output.tf

* Add documentation for demo
* Update Makefile to provide some validation targets
* Update Prometheus values.yaml to remove `myAKSCluster` reference to support multi-cloud
* Add cluster_name output in all modules to support auto-update of kubeconfig in Makefile
* Update comments in custom coredns config
* Fix file reference for mc-demo-manifests.yaml
Use a generic `myCluster` label
---
Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute …

chore(demo): Add to README.md and small fixes to support multi-cloud demo

---

.github/workflows/perf.yaml

This pull request includes changes to the `.github/workflows/perf.yaml` file to add new input parameters for the performance test workflow and update the test commands accordingly. The most important changes include adding `image-registry` and `image-namespace` inputs and modifying the test commands to use these inputs.
Additions to workflow inputs:
* [`.github/workflows/perf.yaml`](diffhunk://#diff-1aa140a875fcb7cae6b4ada7e6e973c4d55179ad046f56465f9f0ec592f283caR9-R19): Added `image-registry` and `image-namespace` inputs to the `workflow_dispatch` section.
Updates to test commands:
* [`.github/workflows/perf.yaml`](diffhunk://#diff-1aa140a875fcb7cae6b4ada7e6e973c4d55179ad046f56465f9f0ec592f283caR57-R64): Updated the test commands in the `jobs:` section to use the new `image-registry` and …

feat: make performance test workflow more configurable

---

.github/workflows/e2e.yaml

Interestingly we were never running this workflow anyways. https://github.com/microsoft/retina/actions/workflows/e2e.yaml?query=is%3Asuccess
This pull request refactors the `.github/workflows/e2e.yaml` file to enhance flexibility and configurability for end-to-end (E2E) tests. The most significant changes include replacing the `workflow_run` trigger with `workflow_call`, introducing configurable inputs and secrets, and updating the E2E job logic to support existing infrastructure reuse.
* Replaced the `workflow_run` trigger with `workflow_call`, allowing the workflow to be invoked with specific inputs such as `image_tag`, `image_registry`, `image_namespace`, and `azure_location`. This enables more dynamic and reusable workflows.
* Added support for optional inputs like …

refactor(e2e): convert E2E workflow to a reusable template

---

pkg/plugin/conntrack/_cprog/conntrack.c

Use only the initial SYN packet to determine the connection direction and not also the SYN-ACK. This should only happen in very unfortunate cases (when the agent is injected in the middle of a TCP handshake).
Just a couple of additional questions:
* Since we don't know the direction, shouldn't this https://github.com/microsoft/retina/blob/7287769254ac5b1597bd617bfb206e8c7047fe3f/pkg/plugin/conntrack/_cprog/conntrack.c#L220 be `TRAFFIC_DIRECTION_UNKNOWN`?
* Is there any particular heuristic behind this ACK detection? https://github.com/microsoft/retina/blob/7287769254ac5b1597bd617bfb206e8c7047fe3f/pkg/plugin/conntrack/_cprog/conntrack.c#L224 Almost all TCP packets should have the ACK flag, so it seems a 50% possibility to get the right direction 
no 
Please add any relevant screenshots or …

fix(conntrack): improve traffic direction detection

---

.github/workflows/images.yaml

Update dev/v0.0.33 branch to push images alongside main
---

ci: update ci for dev/v0.0.33-windows

---

shell/Dockerfile
shell/README.md

Add bpftool to retina shell image
---

chore(shell): add bpftool to shell image

---

.github/workflows/docs.yaml
docs/08-Contributing/02-development.md
site/package-lock.json
site/package.json

Adding the docs build step for every PR
https://github.com/microsoft/retina/actions/runs/15351530012/job/43200699404?pr=1646
---

chore(site): add build doc step for PR

---

go.mod
go.sum
test/e2e/framework/azure/create-cluster-with-npm.go
test/e2e/framework/azure/create-public-ip.go
test/e2e/jobs/jobs.go

Adding azure infrastructure for creating public IP's
---

fix(publicip): Add infrastructure for creating Public IP's

---

controller/Dockerfile
controller/Dockerfile.windows-2019
controller/Dockerfile.windows-2022
controller/Dockerfile.windows-native
controller/Dockerfile.windows-retina-oss-build
operator/Dockerfile.windows-2019
operator/Dockerfile.windows-2022

This pull request updates the Windows base images used in several Dockerfiles across the project to newer versions, ensuring that the builds use the latest security patches and improvements. No other functional or code changes are included.
Updates to Windows base images:
* Updated the `servercore:ltsc2019` image to digest 
[Copilot is generating a summary...]`dfd0f4a06d08d7cad271efcfac0d05ca9dc5fa7c55df15b0d8491c81105974a9` in `controller/Dockerfile`, `controller/Dockerfile.windows-2019`, and `controller/Dockerfile.windows-retina-oss-build`. [[1]](diffhunk://#diff-df234eb86d676bd9233f232e9dc9af4895969477a6a9ff9161e32621f6ce76d1L15-R18) [[2]](diffhunk://#diff-1ca5f5c74f2ae2779bc17c72c3b9e4eea6c410dee21dd74117fef13 …

deps(tls-cve): Upgrade Windows to latest version
